# Disables All Databases Configuration
# Each Database are mapped to individual hosts
do_coturn_db: False
do_grafana_db: False
do_greenlight_db: False
do_moodle_db: False
do_openstreamingplatform_db: False
do_peertube_db: False
do_scalelite_db: False

# Disables Backups
do_redis_backups: False
do_postgres_backups: False

# LetsEncrypt / BigBlueButton email address
bigbluebutton_letsencrypt_address: sammar@worteks.com

# BigBlueButton
do_bbb_webhooks: False
do_bbb_mp4_convert: False

# All Redis are standalone / do not configure Sentinels
redis_standalone: True

# Sets Services Endpoint Names
bbbcsp_fqdn: diffusion.example.com
#coturn_fqdn: turn.example.com
grafana_fqdn: grafana.scaleway.example.com
greenlight_fqdn: bbb.example.com
kibana_fqdn: kibana.scaleway.example.com
peertube_fqdn: video.example.com
prometheus_fqdn: prometheus.scaleway.example.com
scalelite_fqdn: scalelite.example.com

# Faster deployment / weak DH params
# arguably: to disable on reverse & re-generate bbb DH generated by bbb-install.sh
do_unsafe_dhparam: True

# Front Balancer uses Nginx instead of HAProxy
lb_method: nginx

# Turn Server only listens on its public interface
coturn_bind_interface: ens2

# Defines FreeIPA Root Domain
freeipa_domain: scaleway.example.com

# Ensures FreeIPA DNS would be used
install_dns:
- 192.168.255.10
- 192.168.255.11

# Prevents NTP Server Configuration / managed by ipa-client-install
ntp_upstreams: False

# Nginx IP Filter / Backend Services
nginx_backends_ipfilter:
- 51.75.112.172
- 77.204.245.50
- 78.193.67.92

# PeerTube Trusted Proxies
peertube_trust_proxies:
- 127.0.0.1
- 172.16.0.0/12
- 192.168.255.0/24

# Other PeerTube Customizations ...
peertube_instance_businessmodel: "Collect underpants...... step 2, ... and then profit!"
peertube_instance_codeofconduct: "Don't be evil"
peertube_instance_createreason: Streaming BigBlueButton Conferences
peertube_instance_description: Welcome to this PeerTube instance'
peertube_instance_name: BigBlueButtonTube
peertube_instance_short_description: PeerTube, a federated (ActivityPub) video streaming platform using P2P (BitTorrent) directly in the web browser with WebTorrent and Angular.
peertube_instance_terms: No terms for now
peertube_is_nsfw: true

# Don't reconfigure PeerTube
peertube_no_reconfigure: True

# Postgres should trust connections from our private network
postgres_trusted_clients:
- 192.168.255.0/24

# Do not deploy Firehol
# Scaleway Security Groups would deal with firewalling
#setup_firewall: False
# or not... scaleway can't do port ranges?!

# Firehol commons
firehol_private_if: priv0
firehol_trusted_networks:
- 127.0.0.0/24
- 51.75.112.172/32
- 77.204.245.50/32
- 78.193.67.92/32
- 192.168.255.0/24

# FYI. set that one to deploy everything but BBB nodes:
#skip_bbb: True

# WTF moodle?!
# ask raph
peertube_allow_embedded: True

# ElasticSearch nodes have 16G RAM
elasticsearch_jvm_xms: 8g
elasticsearch_jvm_xmx: 8g

# Reverses should not request certs for the following:
expose_alertmanager: False
expose_grafana: False
expose_kibana: False
expose_prometheus: False
expose_scalelite: False

# WTF coturn
# sammar testing stuff...
debug_coturn_all_tls: True
debug_coturn_no_turns_proto: True

# Limits APT Bandwidth to 5MB/s (40000 kb/s)
apt_bw_limit_kb: 40000

# WTF scalelite
# https://github.com/blindsidenetworks/scalelite/pull/546
custom_scalelite_api: True
