# ideally, scalelite services should be spread on several servers
#scalelite_has_roles:
#- api
#- poller
#- recording-importer

#scalelite_images_release: v1

firehol_app_opened_ports:
- name: ssh
  value: tcp/22
- name: http
  value: tcp/80
- name: https
  value: tcp/443
- name: nodexp
  value: tcp/9142
- name: nginxxp
  value: tcp/9143
- name: nginxluaxp
  value: tcp/9145
- name: systemdxp
  value: tcp/9147
- name: bbbxp
  value: tcp/9688
