- name: Installs Redis Backup Script
  template:
    dest: /usr/local/sbin/redis-backup
    group: root
    mode: 0750
    owner: root
    src: backup-db.j2
- name: Installs Redis Backup Job
  copy:
    dest: "/etc/systemd/system/redis-backup.{{ item }}"
    group: root
    mode: 0644
    owner: root
    src: "backup-{{ item }}"
  loop:
  - service
  - timer
  register: bkpunit
- name: Reloads Systemd Configuration
  systemd:
    daemon_reload: yes
  when:
  - bkpunit is defined
  - bkpunit is changed
- name: Enables Redis Backup Job
  service:
    enabled: yes
    name: redis-backup.timer
    state: started
