- name: Installs Redis Server
  apt:
    name: redis-server
    state: present
- name: Installs Sentinel Unit
  copy:
    dest: /etc/systemd/system/redis-sentinel.service
    group: root
    mode: 0644
    owner: root
    src: sentinel.systemd
  register: sentinel_unit
  when:
  - groups[redis_hostgroup] | length > 1
  - not (redis_standalone | default(False))
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']
- name: Removes Sentinel Unit
  file:
    dest: /etc/systemd/system/redis-sentinel.service
    state: absent
  register: sentinel_unit_clean
  when:
  - >
     (redis_standalone | default(False))
     or groups[redis_hostgroup] | length < 2
     or ansible_fqdn in groups['drbd']
     or ansible_hostname in groups['drbd']
     or ansible_nodename in groups['drbd']
- name: Reloads Systemd Configuration
  systemd:
    daemon_reload: yes
  when:
  - >
      (sentinel_unit_clean is defined
       and sentinel_unit_clean is changed)
      or (sentinel_unit is defined
          and sentinel_unit is changed)

- block:
  - name: Ensures Redis is Disabled on DRBD Members
    service:
      enabled: no
      name: redis-server
  - name: Ensures Redis is Stopped on DRBD Backup Members
    service:
      name: redis-server
      state: stopped
    when:
    - not (drbd_is_primary | default(False))
  when:
  - >
      ansible_nodename in groups['drbd']
      or ansible_hostname in groups['drbd']
      or ansible_fqdn in groups['drbd']
