- include_role:
    name: drbd
    tasks_from: facts.yaml
  when:
  - "'drbd1' in ansible_devices"
- include_tasks: install.yaml
- include_tasks: configure.yaml
- include_tasks: server.yaml
- include_tasks: sentinel.yaml
  when:
  - groups[redis_hostgroup] | length > 1
  - not (redis_standalone | default(False))
  - ansible_fqdn not in groups['drbd']
  - ansible_nodename not in groups['drbd']
  - ansible_hostname not in groups['drbd']
- include_tasks: backup.yaml
  when:
  - >
      do_backups | default(False)
      or do_redis_backups | default(False)
- include_tasks: prometheus.yaml
  when:
  - >
      groups['prometheus'] | length > 0
      or do_prometheus | default(False)
