- name: Fetches Redis Exporter
  delay: 5
  get_url:
    dest: "/usr/src/redis-exporter-{{ redis_exporter_release }}.tar.gz"
    group: root
    mode: 0644
    owner: root
    url: "{{ redis_exporter_repo }}/releases/download/v{{ redis_exporter_release }}/redis_exporter-v{{ redis_exporter_release }}.linux-amd64.tar.gz"
  retries: 3
- name: Extracts Redis Exporter
  args:
    chdir: /usr/src
    creates: "/usr/src/redis_exporter-v{{ redis_exporter_release }}.linux-amd64"
    warn: False
  shell: "tar -xzf /usr/src/redis-exporter-{{ redis_exporter_release }}.tar.gz && rm -f /usr/bin/redis_exporter"
- name: Installs Redis Exporter
  copy:
    dest: /usr/bin/redis_exporter
    group: root
    mode: 0755
    owner: root
    remote_src: yes
    src: "/usr/src/redis_exporter-v{{ redis_exporter_release }}.linux-amd64/redis_exporter"
  notify: Reloads Redis Exporter
- name: Creates Redis Exporter Group
  group:
    name: redisexporter
    state: present
- name: Creates Redis Exporter User
  user:
    groups: redisexporter
    name: redisexporter
- name: Installs Redis Exporter Unit
  notify: Reloads Redis Exporter
  register: exporter_unit
  template:
    dest: /etc/systemd/system/redis-exporter.service
    group: root
    mode: 0644
    owner: root
    src: exporter.j2
- name: Reloads Systemd Configuration
  systemd:
    daemon_reload: yes
  when:
  - exporter_unit is defined
  - exporter_unit is changed
- name: Ensures Redis Exporter is Running & Starts on Boot
  service:
    enabled: yes
    name: redis-exporter
    state: started
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_nodename not in groups['drbd']
  - ansible_hostname not in groups['drbd']
- block:
  - name: Ensures Redis Exporter is Disabled on DRBD Members
    service:
      enabled: no
      name: redis-exporter
  - name: Ensures Redis Exporter is Stopped on DRBD Backup Members
    service:
      name: redis-exporter
      state: stopped
    when:
    - not (drbd_is_primary | default(False))
  - include_role:
      name: pacemaker
      tasks_from: add-service.yaml
    loop: "{{ redis_drbd_groups }}"
    loop_control:
      loop_var: apply_to
    vars:
      service_id: Redisxp-rsc
      service_name: redis-exporter
      service_type: systemd
    when:
    - groups[apply_to] | length > 0
    - >
        ansible_nodename in groups[apply_to]
        or ansible_hostname in groups[apply_to]
        or ansible_fqdn in groups[apply_to]
  - include_role:
      name: pacemaker
      tasks_from: finish-setup.yaml
    vars:
      drbd_facts_reset: False
    loop: "{{ redis_drbd_groups }}"
    loop_control:
      loop_var: apply_to
    when:
    - groups[apply_to] | length > 0
    - >
        ansible_nodename in groups[apply_to]
        or ansible_hostname in groups[apply_to]
        or ansible_fqdn in groups[apply_to]
  when:
  - >
      ansible_fqdn in groups['drbd']
      or ansible_hostname in groups['drbd']
      or ansible_nodename in groups['drbd']
