- name: Installs Redis Configuration
  notify: Reloads Redis
  template:
    dest: /etc/redis/redis.conf
    group: root
    mode: 0644
    owner: root
    src: redis.j2
- name: Ensures Redis Server is Running & Starts on Boot
  service:
    enabled: yes
    name: redis-server
    state: started
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']
