dependencies:
- role: docker
- role: nginx
  when:
  - >
     not (ansible_fqdn in groups['bbb']
          and ansible_fqdn in groups['greenlight'])
  - >
     not (ansible_hostname in groups['bbb']
          and ansible_hostname in groups['greenlight'])
