- include_role:
    name: drbd
    tasks_from: facts.yaml
  when:
  - "'drbd1' in ansible_devices"
- include_tasks: facts.yaml
- include_tasks: install.yaml
- include_role:
    name: commons
    tasks_from: certs-trusted.yaml
- include_role:
    name: certbot
  when:
  - not (bbb_uses_selfsigned | default(True))
- include_role:
    name: pki
    tasks_from: install-cert.yaml
  when:
  - bbb_uses_selfsigned | default(True)
- include_tasks: configure.yaml
- include_tasks: hardening.yaml
- include_tasks: prometheus.yaml
  when:
  - >
      groups['prometheus'] | length > 0
      or do_prometheus | default(False)
