elasticsearch_cluster_name: es-bbb

elasticsearch_exporter_release: 1.1.0
elasticsearch_exporter_port: 9114

elasticsearch_images_release: 7.12.0
elasticsearch_images_repo: docker.elastic.co/elasticsearch/elasticsearch

elasticsearch_jvm_xms: 512m
elasticsearch_jvm_xmx: 512m
