- include_tasks: facts.yaml
- include_tasks: install.yaml
- include_tasks: configure.yaml
- include_tasks: prometheus.yaml
  when:
  - >
      groups['prometheus'] | length > 0
      or do_prometheus | default(False)
