- name: Creates Grafana Group
  group:
    name: grafana
    state: present
- name: Creates Grafana User
  user:
    groups: grafana
    name: grafana
- name: Resolves Grafana User ID
  changed_when: False
  register: grafana_user_id
  shell: "getent passwd grafana | awk -F: '{print $3;exit;}'"
- name: Installs Grafana Server Configuration Directories
  file:
    dest: "{{ fl }}"
    group: root
    mode: 0755
    owner: root
    state: directory
  loop:
  - /etc/grafana
  - /etc/grafana/bbb-dashboards
  - /etc/grafana/provisioning
  - /etc/grafana/provisioning/dashboards
  - /etc/grafana/provisioning/datasources
  - /etc/grafana/provisioning/notifiers
  - /etc/grafana/provisioning/plugins
  loop_control:
    loop_var: fl
- name: Installs Grafana Database Directory
  file:
    dest: /var/lib/grafana
    group: grafana
    mode: 0755
    owner: grafana
    state: directory
