- hosts: reverse
  vars:
    corosync_members:
    - reverse-1.scaleway.example.com
    - reverse-2.scaleway.example.com
    corosync_multicast_address: 239.255.1.1
  roles:
  - pacemaker
- hosts: postgres_peertube
  vars:
    corosync_members:
    - peertube-db-1.scaleway.example.com
    - peertube-db-2.scaleway.example.com
    corosync_multicast_address: 239.255.1.2
  roles:
  - pacemaker
- hosts: postgres_scalelite
  vars:
    corosync_members:
    - scalelite-db-1.scaleway.example.com
    - scalelite-db-2.scaleway.example.com
    corosync_multicast_address: 239.255.1.3
  roles:
  - pacemaker
- hosts: postgres_greenlight
  vars:
    corosync_members:
    - greenlight-1.scaleway.example.com
    - greenlight-2.scaleway.example.com
    corosync_multicast_address: 239.255.1.6
  roles:
  - pacemaker
- hosts: peertube
  vars:
    corosync_members:
    - peertube-1.scaleway.example.com
    - peertube-2.scaleway.example.com
    corosync_multicast_address: 239.255.1.4
  roles:
  - pacemaker
- hosts: scalelite
  vars:
    corosync_members:
    - scalelite-1.scaleway.example.com
    - scalelite-2.scaleway.example.com
    corosync_multicast_address: 239.255.1.5
  roles:
  - pacemaker
- hosts: bbbcsp
  vars:
    corosync_members:
    - csp-1.scaleway.example.com
    - csp-2.scaleway.example.com
    corosync_multicast_address: 239.255.1.7
  roles:
  - pacemaker
