groups:
- name: KubernetesElasticSearch
  rules:
  - alert: ElasticSearchNodeDown
    expr: elasticsearch_node_stats_up == 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "ElasticSearch Node down (instance {{ $labels.instance }})"
      description: "ElasticSearch Node is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticSearchClusterDown
    expr: elasticsearch_clustersettings_stats_up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "ElasticSearch Cluster down (instance {{ $labels.instance }})"
      description: "ElasticSearch Cluster is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchHeapUsageTooHigh
    expr: (elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}) * 100 > 90
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Elasticsearch Heap Usage Too High (instance {{ $labels.instance }})"
      description: "The heap usage is over 90%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchHeapUsageWarning
    expr: (elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}) * 100 > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Elasticsearch Heap Usage warning (instance {{ $labels.instance }})"
      description: "The heap usage is over 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
# FIXME: k8s specific
#  - alert: ElasticsearchMemoryCritical
#    expr: 100 * (sum by (kubernetes_cluster,kubernetes_pod_name) (elasticsearch_jvm_memory_used_bytes)) / on (kubernetes_cluster,kubernetes_pod_name) group_left() sum by (kubernetes_cluster,kubernetes_pod_name) (label_replace(container_spec_memory_limit_bytes{pod=~"elasticsearch.+",container=""},"kubernetes_pod_name","$1","pod","(.+)")) > 90
#    for: 5m
#    labels:
#      severity: critical
#    annotations:
#      summary: "Elasticsearch Memory Usage Too High (instance {{ $labels.instance }})"
#      description: "Memory usage is over 90% for 5m\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
#  - alert: ElasticsearchMemoryWarning
#    expr: 100 * (sum by (kubernetes_cluster,kubernetes_pod_name) (elasticsearch_jvm_memory_used_bytes)) / on (kubernetes_cluster,kubernetes_pod_name) group_left() sum by (kubernetes_cluster,kubernetes_pod_name) (label_replace(container_spec_memory_limit_bytes{pod=~"elasticsearch.+",container=""},"kubernetes_pod_name","$1","pod","(.+)")) > 80
#    for: 5m
#    labels:
#      severity: warning
#    annotations:
#      summary: "Elasticsearch Memory Usage warning (instance {{ $labels.instance }})"
#      description: "Memory usage is over 80% for 5m\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchDiskSpaceLow
    expr: elasticsearch_filesystem_data_available_bytes / elasticsearch_filesystem_data_size_bytes * 100 < 30
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Elasticsearch disk space low (instance {{ $labels.instance }})"
      description: "The disk usage is over 70%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchDiskOutOfSpace
    expr: elasticsearch_filesystem_data_available_bytes / elasticsearch_filesystem_data_size_bytes * 100 < 21
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Elasticsearch disk out of space (instance {{ $labels.instance }})"
      description: "The disk usage is reaching 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchClusterRed
    expr: elasticsearch_cluster_health_status{color="red"} == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Elasticsearch Cluster Red (instance {{ $labels.instance }})"
      description: "Elastic Cluster Red status\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchClusterYellow
    expr: elasticsearch_cluster_health_status{color="yellow"} == 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Elasticsearch Cluster Yellow (instance {{ $labels.instance }})"
      description: "Elastic Cluster Yellow status\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchRelocationShards
    expr: elasticsearch_cluster_health_relocating_shards > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Elasticsearch relocating shards (instance {{ $labels.instance }})"
      description: "Elasticsearch is relocating shards\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchInitializingShards
    expr: elasticsearch_cluster_health_initializing_shards > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Elasticsearch initializing shards (instance {{ $labels.instance }})"
      description: "Elasticsearch is initializing shards\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchUnassignedShards
    expr: elasticsearch_cluster_health_unassigned_shards > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Elasticsearch unassigned shards (instance {{ $labels.instance }})"
      description: "Elasticsearch has unassigned shards\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: ElasticsearchPendingTasks
    expr: elasticsearch_cluster_health_number_of_pending_tasks > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Elasticsearch pending tasks (instance {{ $labels.instance }})"
      description: "Elasticsearch has pending tasks. Cluster works slowly.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
#  - alert: ElasticsearchNoNewDocuments
#    expr: increase(elasticsearch_indices_docs{es_data_node="true"}[24h]) < 1
#    for: 5m
#    labels:
#      severity: warning
#    annotations:
#      summary: "Elasticsearch no new documents (instance {{ $labels.instance }})"
#      description: "No new documents for 60 min!\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
