groups:
- name: PaceMaker
  rules:
  - alert: PaceMakerFailedResources
    expr: count(ha_cluster_pacemaker_resources{status="failed"} == 1) > 0
    labels:
      severity: warning
    annotations:
      summary: "Resource {{ $labels.resource }}@{{ $labels.node }} on cluster {{ $labels.pcm_cluster }}"
      description: "Cluster {{ $labels.pcm_cluster }}, resource {{ $labels.resources }} is down on {{ $labels.node }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PaceMakerMigrationThresholdExceeded
    expr: count(ha_cluster_pacemaker_fail_count > ha_cluster_pacemaker_migration_threshold) > 0
    labels:
      severity: warning
    annotations:
      summary: "Resource Migration Threshold Exceeded"
      description: "A resource fail count exceeded its migration threshold"
  - alert: PaceMakerServiceDown
    expr: node_systemd_unit_state{name="pacemaker.service", state="active"} == 0
    labels:
      severity: critical
    annotations:
      summary: "Pacemaker service not running (instance {{ $labels.instance }}"
      description: "Pacemaker service inactive\n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PaceMakerCorosyncServiceDown
    expr: node_systemd_unit_state{name="corosync.service", state="active"} == 0
    labels:
      severity: critical
    annotations:
      summary: "Corosync service not running (instance {{ $labels.instance }}"
      description: "Corosync service inactive\n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PaceMakerSbdServiceDown
    expr: node_systemd_unit_state{name="sbd.service", state="active"} == 0
    labels:
      severity: critical
    annotations:
      summary: "Sbd service not running (instance {{ $labels.instance }}"
      description: "Sbd service inactive\n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PaceMakerHawkServiceDown
    expr: node_systemd_unit_state{name="hawk.service", state="active"} == 0
    labels:
      severity: critical
    annotations:
      summary: "Hawk service not running (instance {{ $labels.instance }}"
      description: "Hawk service inactive\n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PaceMakerHawkBackendServiceDown
    expr: node_systemd_unit_state{name="hawk-backend.service", state="active"} == 0
    labels:
      severity: critical
    annotations:
      summary: "Hawk Backend service not running (instance {{ $labels.instance }}"
      description: "Hawk Backend service inactive\n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PaceMakerExporterServiceDown
    expr: node_systemd_unit_state{name="ha-cluster-exporter.service", state="active"} == 0
    labels:
      severity: warning
    annotations:
      summary: "HA Cluster Exporter service not running (instance {{ $labels.instance }}"
      description: "HA Cluster Exporter service inactive\n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
  - alert: PaceMakerLocationConstraints
    expr: ha_cluster_pacemaker_location_constraints < 0
    labels:
      severity: warning
    annotations:
      summary: "A negative resource location constraint has been detected (instance {{ $labels.instance }})"
      description: "A negative resource location constraint has been detected. Please ensure that no resource has been mistakenly banned from a node.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

# our DRBD version is too old / ha_cluster_exporter won't collect those metrics
#  - alert: PaceMakerDrbdConnectionBadState
#    expr: count(ha_cluster_drbd_connections{peer_disk_state=~"inconsistent|outdated|dunknown|failed"}) > 0
#    labels:
#      severity: warning
#    annotations:
#      summary: "A DRBD connection is in a bad state (instance {{ $labels.node }})"
#      description: "Cluster {{ $labels.pcm_cluster }} DRBD connection should be checked\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
#  - alert: PaceMakerDrbdSync
#    expr: ha_cluster_drbd_connections_sync < 90
#    labels:
#      severity: warning
#    annotations:
#      summary: "A DRBD disk sync is lower than 90% (instance {{ $labels.node }})"
#      description: "Cluster {{ $labels.pcm_cluster }} DRBD device should be checked\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
#  - alert: PaceMakerDrbdResourceBadState
#    expr: count(ha_cluster_drbd_resources{peer_disk_state=~"inconsistent|outdated|dunknown|failed"}) > 0
#    labels:
#      severity: warning
#    annotations:
#      summary: "A DRBD resource is in a bad state (instance {{ $labels.node }})"
#      description: "Cluster {{ $labels.pcm_cluster }} DRBD resource should be checked\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

# Stonith is disabled by Ansible
#  - alert: PaceMakerStonithDisabled
#    expr: ha_cluster_pacemaker_stonith_enabled == 0
#    labels:
#      severity: warning
#    annotations:
#      summary: "STONITH is disabled (instance {{ $labels.instance }})"
#      description: "STONITH is disabled! Clusters without a fencing mechanism are not supported and have increased risk of data loss.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
