groups:
- name: Turn
  rules:
  - alert: TurnNotRunning
    expr: systemd_unit_state{name="coturn.service",state!="active"} > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Turn Server not running (instance {{ $labels.instance }})"
      description: "Turn Server Service is DOWN.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
