- name: Installs Td-Agent Restart Script
  copy:
    dest: /usr/local/sbin/tdagent-reload
    group: root
    mode: 0750
    owner: root
    src: td-agent-reload.sh
- name: Installs Td-Agent Restart Job
  copy:
    dest: "/etc/systemd/system/td-agent-reload.{{ item }}"
    group: root
    mode: 0644
    owner: root
    src: "td-agent-reload.{{ item }}"
  loop:
  - service
  - timer
  register: hkunit
- name: Reloads Systemd Configuration
  shell: systemctl daemon-reload
  when:
  - hkunit is defined
  - hkunit is changed
- name: Enables Td-Agent Restart Job
  service:
    enabled: yes
    name: td-agent-reload.timer
    state: started
