- name: Reloads Redis
  service:
    name: redis-server
    state: restarted
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']
- name: Reloads Sentinel
  service:
    name: redis-sentinel
    state: restarted
  when:
  - groups[redis_hostgroup] | length > 1
  - not (redis_standalone | default(False))
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']
- name: Reloads Redis Exporter
  service:
    name: redis-exporter
    state: restarted
  when:
  - >
       (redis_exporter_should_run | default(False)
        and (ansible_fqdn in groups['drbd']
             or ansible_nodename in groups['drbd']
             or ansible_hostname in groups['drbd']))
       or (ansible_fqdn not in groups['drbd']
          and ansible_nodename not in groups['drbd']
          and ansible_hostname not in groups['drbd'])
