- name: Reloads Redis
  service:
    name: redis-server
    state: restarted
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']
- name: Reloads Sentinel
  service:
    name: redis-sentinel
    state: restarted
  when:
  - groups[redis_hostgroup] | length > 1
  - not (redis_standalone | default(False))
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']
- name: Reloads Redis Exporter
  service:
    name: redis-exporter
    state: restarted
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_nodename not in groups['drbd']
  - ansible_hostname not in groups['drbd']
