- name: Installs DRBD Configuration
  template:
    dest: "/etc/drbd.d/{{ drbd_resource_name }}.res"
    force: no
    group: root
    mode: 0644
    owner: root
    src: resource.j2
- name: Tests State of DRBD Resource
  args:
    executable: /bin/bash
  changed_when: False
  failed_when: False
  register: dstate
  shell: |
    set -o pipefail && \
    drbdadm dstate {{ drbd_resource_name }} 2>&1 | grep -E "(No valid meta data found|Unconfigured)"
- block:
  - name: Initializes Device Metadata
    shell: |
      echo yes | drbdadm create-md {{ drbd_resource_name }}
  - include_tasks: up.yaml
  - include_tasks: make-primary.yaml
  when:
  - dstate is defined
  - dstate.rc is defined
  - (dstate.rc | default(1)) == 0
- include_role:
    name: pacemaker
    tasks_from: add-drbd.yaml
  vars:
    drbd_id: "{{ corosync_drbd_id | default('r0') }}"
    drbd_name: "{{ drbd_resource_name }}"
  when:
  - corosync_hostgroup | default(False)
