- name: Fail if Runtime mismatches Ansible Configuration
  fail:
    msg: |
      Found a DRBD device on {{ ansible_nodename }}, which is not a member
      of the drbd host group
  when:
  - ansible_fqdn not in groups['drbd']
- name: Checks DRBD Status
  changed_when: False
  failed_when: False
  register: drbdproc
  shell: "grep ro:Primary /proc/drbd"
- name: Sets DRBD Facts
  set_fact:
    drbd_is_primary: "{{ True if (drbdproc is defined
                                  and drbdproc.rc is defined
                                  and (drbdproc.rc | default(1)) == 0)
                              else False }}"
