- include_tasks: facts.yaml
- name: Fixes lvm.conf ignoring DRBD parent devices
  template:
    dest: /etc/lvm/lvm.conf
    group: root
    mode: 0644
    owner: root
    src: lvm.j2
- block:
  - name: Checks for Existing PV
    changed_when: False
    failed_when: False
    register: haspv
    shell: pvs | grep /dev/drbd1
  - name: Creates PV
    any_errors_fatal: true
    shell: pvcreate /dev/drbd1
    when:
    - haspv is defined
    - haspv.rc is defined
    - (haspv.rc | default(0)) != 0
  - name: Checks for Existing VG
    changed_when: False
    failed_when: False
    register: hasvg
    shell: |
      vgs | grep "{{ drbd_vg_name | default('data') }}"
  - name: Creates VG
    any_errors_fatal: true
    shell: |
      vgcreate "{{ drbd_vg_name | default('data') }}" /dev/drbd1
    when:
    - hasvg is defined
    - hasvg.rc is defined
    - (hasvg.rc | default(0)) != 0
  - include_role:
      name: pacemaker
      tasks_from: add-vg.yaml
    vars:
      vg_id: "{{ corosync_drbd_id | default('r0') }}"
      vg_name: "{{ drbd_vg_name | default('data') }}"
    when:
    - corosync_hostgroup | default(False)
  - include_tasks: filesystem.yaml
    loop: "{{ drbd_filesystems }}"
    loop_control:
      index_var: devidx
      loop_var: fs
    vars:
      lvm_id: "{{ (devidx | int) + 1 }}"
      vg_name: "{{ drbd_vg_name | default('data') }}"
  - include_role:
      name: pacemaker
      tasks_from: finish-setup.yaml
  when: drbd_is_primary | default(False)
