- block:
  - name: Starts DRBD Resource
    command: |
      drbdadm up {{ drbd_resource_name }}
    delay: 10
    register: drbduprslt
    retries: 3
    until: drbduprslt.rc == 0
  - name: Gives it a few seconds
    delegate_to: "{{ corosync_members[0] }}"
    pause:
      seconds: 5
    run_once: yes
  when:
  - drbd_resource_name | default(False)
  - corosync_members is defined
  - corosync_members | length > 0
