- name: Gather Facts from NFS Server
  delegate_to: "{{ groups['nfs'][0] }}"
  delegate_facts: True
  run_once: yes
  setup:
  when:
  - groups['nfs'] | length > 0
- name: Gather Facts from LBs
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['lb'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['lb'] | length > 0
- name: Gather Facts from Postgres
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['postgres_scalelite'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
- name: Gather Facts from Redis
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['redis_scalelite'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['lb'] | length == 0
- name: Gather Facts from BigBlueButton
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['bbb'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  vars:
    ansible_python_interpreter: /usr/bin/python
  when:
  - groups['bbb'] | length > 0
  - not (skip_bbb | default(False))
