- block:
  - name: "Fetches BigBlueButton Public SSH Key fom {{ srv }}"
    args:
      chdir: /home/bigbluebutton/.ssh
    changed_when: False
    delay: 5
    delegate_to: "{{ srv }}"
    register: has_key
    retries: 3
    run_once: yes
    shell: cat id_rsa.pub 2>/dev/null
    vars:
      ansible_python_interpreter: "/usr/bin/{{ 'python'
                                                 if (hostvars[srv]['ansible_distribution_release'] == 'xenial')
                                                 else 'python3' }}"
  - name: "Ensures {{ srv }} Key is Trusted"
    lineinfile:
      create: yes
      dest: "/home/scalelite-spool/.ssh/{{ keyfile }}"
      line: "{{ has_key.stdout_lines[0] }}"
    loop:
    - authorized_keys
    - instance_keys
    loop_control:
      loop_var: keyfile
  when:
  - hostvars[srv] is defined
  - hostvars[srv]['ansible_distribution_release'] is defined
