- include_role:
    name: drbd
    tasks_from: facts.yaml
  when:
  - "'drbd1' in ansible_devices"
- include_tasks: ./init-bbb.yaml
  loop: "{{ groups['bbb'] }}"
  loop_control:
    loop_var: bbb_remote
