- name: "Fetches Secret from {{ bbb_remote }}"
  changed_when: False
  delegate_to: "{{ bbb_remote }}"
  register: bbb_secret
  run_once: yes
  shell: bbb-conf --secret | awk '/Secret:/{print $2}'
- name: "Fetches URL from {{ bbb_remote }}"
  changed_when: False
  delegate_to: "{{ bbb_remote }}"
  register: bbb_url
  run_once: yes
  shell: bbb-conf --secret | awk '/URL:/{print $2}'

- name: "Checks {{ bbb_remote }} Registered (main)"
  changed_when: False
  delegate_to: "{{ groups['scalelite'][0] }}"
  failed_when: False
  register: has_remote
  run_once: yes
  shell: "docker exec -i scalelite-api bundle exec rake servers | grep {{ bbb_url.stdout_lines[0] }}"
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']
- name: "Checks {{ bbb_remote }} Registered (DRBD)"
  changed_when: False
  failed_when: False
  register: drbd_has_remote
  shell: "docker exec -i scalelite-api bundle exec rake servers | grep {{ bbb_url.stdout_lines[0] }}"
  when:
  - >
      ansible_fqdn in groups['drbd']
      or ansible_hostname in groups['drbd']
      or ansible_nodename in groups['drbd']
  - drbd_is_primary | default(False)

# Register server to Scalelite without DRBD
- block:
  - name: "Registers {{ bbb_remote }}"
    delegate_to: "{{ groups['scalelite'][0] }}"
    run_once: yes
    shell: docker exec -i scalelite-api bundle exec rake servers:add[{{ bbb_url.stdout_lines[0] }}api/,{{ bbb_secret.stdout_lines[0] }}]
  - name: "Resolves {{ bbb_remote }} ID"
    changed_when: False
    delegate_to: "{{ groups['scalelite'][0] }}"
    failed_when: False
    register: remote_id
    run_once: yes
    shell: "docker exec -i scalelite-api bundle exec rake servers | grep -B1 {{ bbb_url.stdout_lines[0] }} | awk '/id:/{print $2}'"
  - name: "Enables {{ bbb_remote }}"
    delegate_to: "{{ groups['scalelite'][0] }}"
    run_once: yes
    shell: "docker exec -i scalelite-api bundle exec rake servers:enable[{{ remote_id.stdout_lines[0] }}]"
  when:
  - has_remote is defined
  - has_remote.rc is defined
  - has_remote.rc != 0

# Register server to Scalelite with DRBD
- block:
  - name: "Registers {{ bbb_remote }}"
    shell: docker exec -i scalelite-api bundle exec rake servers:add[{{ bbb_url.stdout_lines[0] }}api/,{{ bbb_secret.stdout_lines[0] }}]
  - name: "Resolves {{ bbb_remote }} ID"
    changed_when: False
    failed_when: False
    register: remote_id
    shell: "docker exec -i scalelite-api bundle exec rake servers | grep -B1 {{ bbb_url.stdout_lines[0] }} | awk '/id:/{print $2}'"
  - name: "Enables {{ bbb_remote }}"
    shell: "docker exec -i scalelite-api bundle exec rake servers:enable[{{ remote_id.stdout_lines[0] }}]"
  when:
  - drbd_has_remote is defined
  - drbd_has_remote.rc is defined
  - drbd_has_remote.rc != 0

# Updates server to Scalelite without DRBD
- block:
  - name: "Checks {{ bbb_remote }} Status"
    changed_when: False
    failed_when: False
    register: remote_active
    shell: "docker exec -i scalelite-api bundle exec rake servers | grep -A3 {{ bbb_url.stdout_lines[0] }} | grep enabled"
  - block:
    - name: "Resolves {{ bbb_remote }} ID"
      changed_when: False
      failed_when: False
      register: remote_id
      shell: "docker exec -i scalelite-api bundle exec rake servers | grep -B1 {{ bbb_url.stdout_lines[0] }} | awk '/id:/{print $2}'"
    - name: "Enables {{ bbb_remote }}"
      shell: "docker exec -i scalelite-api bundle exec rake servers:enable[{{ remote_id.stdout_lines[0] }}]"
    when:
    - remote_active is defined
    - remote_active.rc is defined
    - remote_active.rc != 0
  when:
  - has_remote is defined
  - has_remote.rc is defined
  - has_remote.rc == 0

# Updates server to Scalelite with DRBD
- block:
  - name: "Checks {{ bbb_remote }} Status"
    changed_when: False
    failed_when: False
    register: remote_active
    shell: "docker exec -i scalelite-api bundle exec rake servers | grep -A3 {{ bbb_url.stdout_lines[0] }} | grep enabled"
  - block:
    - name: "Resolves {{ bbb_remote }} ID"
      changed_when: False
      failed_when: False
      register: remote_id
      shell: "docker exec -i scalelite-api bundle exec rake servers | grep -B1 {{ bbb_url.stdout_lines[0] }} | awk '/id:/{print $2}'"
    - name: "Enables {{ bbb_remote }}"
      shell: "docker exec -i scalelite-api bundle exec rake servers:enable[{{ remote_id.stdout_lines[0] }}]"
    when:
    - remote_active is defined
    - remote_active.rc is defined
    - remote_active.rc != 0
  when:
  - drbd_has_remote is defined
  - drbd_has_remote.rc is defined
  - drbd_has_remote.rc == 0
