- block:
  - name: Waits for Scalelite API
    changed_when: False
    delegate_to: "{{ groups['scalelite'][0] }}"
    register: is_started
    retries: 20
    run_once: yes
    shell: docker exec -it scalelite-api uptime
    until: is_started.rc == 0
  - name: Initializes Scalelite Database
    args:
      chdir: /etc/docker-compose/scalelite
      creates: /etc/docker-compose/scalelite/db-init.log
    delegate_to: "{{ groups['scalelite'][0] }}"
    run_once: yes
    shell: |
      docker exec -i scalelite-api bundle exec rake db:setup >db-init.log 2>&1;
      echo init >db-upgrade-{{ scalelite_images_release }}.log 2>&1
  - name: Updates Scalelite Database
    args:
      chdir: /etc/docker-compose/scalelite
      creates: "/etc/docker-compose/scalelite/db-upgrade-{{ scalelite_images_release }}.log"
    delegate_to: "{{ groups['scalelite'][0] }}"
    run_once: yes
    shell: |
      docker exec -i scalelite-api bundle exec rake db:migrate >db-upgrade-{{ scalelite_images_release }}.log 2>&1
  when:
  - ansible_nodename not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_fqdn not in groups['drbd']
- block:
  - name: Waits for Scalelite API
    changed_when: False
    register: is_started
    retries: 20
    shell: docker exec -it scalelite-api uptime
    until: is_started.rc == 0
  - name: Initializes Scalelite Database
    args:
      chdir: /etc/docker-compose/scalelite
      creates: /etc/docker-compose/scalelite/db-init.log
    shell: |
      docker exec -i scalelite-api bundle exec rake db:setup >db-init.log 2>&1;
      echo init >db-upgrade-{{ scalelite_images_release }}.log 2>&1
  - name: Marks DB initialized on other DRBD members
    copy:
      content: "# Done on DRBD primary node"
      dest: /etc/docker-compose/scalelite/db-init.log
      force: no
      group: root
      mode: 0644
      owner: root
  - block:
    - name: Updates Scalelite Database
      args:
        chdir: /etc/docker-compose/scalelite
        creates: "/etc/docker-compose/scalelite/db-upgrade-{{ scalelite_images_release }}.log"
      shell: |
        docker exec -i scalelite-api bundle exec rake db:migrate >db-upgrade-{{ scalelite_images_release }}.log 2>&1
    - name: Marks DB upgraded on other DRBD members
      copy:
        content: "# Done on DRBD primary node"
        dest: "/etc/docker-compose/scalelite/db-upgrade-{{ scalelite_images_release }}.log"
        force: no
        group: root
        mode: 0644
        owner: root
  when:
  - >
      ansible_nodename in groups['drbd']
      or ansible_hostname in groups['drbd']
      or ansible_fqdn in groups['drbd']
  - drbd_is_primary | default(False)
