- include_role:
    name: drbd
    tasks_from: facts.yaml
  when:
  - "'drbd1' in ansible_devices"
- include_tasks: facts.yaml
- include_tasks: ssh.yaml
- include_tasks: storage.yaml
- include_tasks: api.yaml
  when:
  - "'api' in scalelite_has_roles"
- include_tasks: poller.yaml
  when:
  - "'poller' in scalelite_has_roles"
- include_tasks: recording-importer.yaml
  when:
  - "'recording-importer' in scalelite_has_roles"
- block:
  - include_tasks: nginx.yaml
  - include_tasks: utils.yaml
  when:
  - "'api' in scalelite_has_roles"
- include_tasks: compose.yaml
- include_tasks: init-setup.yaml
- include_tasks: prometheus.yaml
  when:
  - >
      groups['prometheus'] | length > 0
      or do_prometheus | default(False)
