- include_tasks: facts.yaml
- include_tasks: ssh.yaml
- include_tasks: storage.yaml
- include_tasks: api.yaml
  when:
  - "'api' in scalelite_has_roles"
- include_tasks: poller.yaml
  when:
  - "'poller' in scalelite_has_roles"
- include_tasks: recording-importer.yaml
  when:
  - "'recording-importer' in scalelite_has_roles"
- block:
  - include_tasks: nginx.yaml
  - include_tasks: certbot.yaml
    when:
    - not (bbb_uses_selfsigned | default(True))
  - include_role:
      name: pki
      tasks_from: install-cert.yaml
    when:
    - bbb_uses_selfsigned | default(True)
  when:
  - "'nginx' in scalelite_has_roles"
- include_tasks: compose.yaml
- include_tasks: init-setup.yaml
- include_tasks: prometheus.yaml
  when:
  - >
      groups['prometheus'] | length > 0
      or do_prometheus | default(False)
