- name: Checks for Existing NFS Mount
  changed_when: False
  command: |
    grep ' /var/scalelite-recordings ' /etc/mtab
  failed_when: False
  register: has_nfs
- block:
  - name: Installs NFS Client
    apt:
      name: nfs-common
      state: present
  - name: Ensures NFS Mount Directory Exists
    file:
      dest: /var/scalelite-recordings
      group: root
      mode: 0755
      owner: root
      state: directory
  - name: Sets NFS Facts
    set_fact:
      sdir: "{{ hostvars[groups['nfs'][0]]['nfs_exports_root'] | default(nfs_exports_root) }}"
      shost: "{{ hostvars[groups['nfs'][0]]['ansible_default_ipv4']['address'] }}"
      sopts: "noatime,nodiratime,noexec,nodev,nosuid"
  - name: Adds NFS Mount to /etc/fstab
    lineinfile:
      dest: /etc/fstab
      line: "{{ shost }}:{{ sdir }} /var/scalelite-recordings nfs {{ sopts }} 0 0"
      regexp: " /var/scalelite-recordings "
  - name: Ensures Scalelite Directories Present
    delegate_to: "{{ groups['nfs'][0] }}"
    file:
      dest: "{{ sdir }}/{{ sub }}"
      group: 2000
      mode: 0775
      owner: 2000
      state: directory
    loop:
    - published
    - spool
    loop_control:
      loop_var: sub
    run_once: yes
  - name: Mounts NFS Share
    mount:
      path: /var/scalelite-recordings
      state: mounted
  when:
  - has_nfs is defined
  - has_nfs.rc is defined
  - has_nfs.rc != 0
