- name: Installs Scalelite Virtualhost
  notify: Reloads Nginx
  template:
    dest: /etc/nginx/sites-available/scalelite.conf
    group: root
    mode: 0644
    owner: root
    src: vhost.j2
- name: Enables Scalelite Virtualhost
  file:
    dest: /etc/nginx/sites-enabled/scalelite.conf
    src: /etc/nginx/sites-available/scalelite.conf
    state: link
  notify: Reloads Nginx
- name: Checks for Playbacks Directory
  changed_when: False
  failed_when: False
  stat:
    path: /var/scalelite-recordings/playback
  register: hasplaybacks
- block:
  - name: Starts Scalelite Nginx Container
    shell: |
      docker rm -f extractplaybacks || echo OK;
      docker run --entrypoint /bin/sh \
          --name extractplaybacks \
          -d "{{ scalelite_images_repo }}:{{ scalelite_images_release }}-nginx" \
          -c "sleep 86400"
  - name: Extracts Scalelite Playbacks
    shell: docker cp extractplaybacks:/var/bigbluebutton/playback /var/scalelite-recordings/playback
  - name: Terminates Scalelite Nginx Container
    shell: docker rm -f extractplaybacks
  when:
  - hasplaybacks is defined
  - hasplaybacks.stat is defined
  - not hasplaybacks.stat.exists
  - >
      (ansible_fqdn not in groups['drbd'])
      or (ansible_fqdn in groups['drbd']
          and drbd_is_primary | default(False))
