- block:
  - include_tasks: sshfs.yaml
    when:
    - groups['sshfs'] | length > 0

  - include_tasks: nfs-client.yaml
    when:
    - groups['sshfs'] | length == 0
    - groups['nfs'] | length > 0
  #TODO:
  #- include_tasks: cephfs-client.yaml
  #  when:
  #  - groups['cephfs'] | length > 0
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']

- name: Ensures Scalelite Working Directories Exist
  file:
    dest: "/var/scalelite-recordings/{{ fl }}"
    group: scalelite-spool
    mode: 0755
    owner: scalelite-spool
    state: directory
  loop:
  - published
  - recording
  - recording/scalelite
  - spool
  - unpublished
  loop_control:
    loop_var: fl
  when:
  - groups['nfs'] | length == 0
  - groups['sshfs'] | length == 0
  - >
      (ansible_fqdn not in groups['drbd']
       and ansible_hostname not in groups['drbd']
       and ansible_nodename not in groups['drbd'])
      or ((ansible_fqdn in groups['drbd']
           or ansible_hostname in groups['drbd']
           or ansible_nodename in groups['drbd'])
          and drbd_is_primary | default(False))

- include_role:
    name: commons
    tasks_from: swap.yaml
  vars:
    swap_size: 4006
