nginx_drbd_should_run: False

nginx_exporter_port: 9143
nginx_exporter_release: 0.8.0
nginx_exporter_repo: https://github.com/nginxinc/nginx-prometheus-exporter

nginx_lua_exporter_port: 9145
nginx_lua_exporter_shared: 10M

nginx_names_bucket_hash: 128
nginx_stats_port: 8080
nginx_worker_connections: 768
