{
 "title": "BigBlueButton",
 "description": "BigBlueButton metrics overview.",
 "tags": [
  "Application",
  "BigBlueButton"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "kind",
    "label": "Component",
    "query": "label_values(bbb_api_up,target_type)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bbb_api_up{target_type=~\"$kind\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_api_up{target_type=~\"$kind\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (bbb_meetings_participants{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BigBlueButton Exporter Version",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "targets": [
    { "expr": "bbb_exporter", "legendFormat": "{{instance}} | {{version}}" }
   ]
  },
  {
   "title": "Total Participants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bbb_meetings_participants{target_type=\"bigbluebutton\",instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (bbb_meetings_voice_participants{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (bbb_meetings_video_participants{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Rooms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bbb_room_participants_gcount{target_type=\"bigbluebutton\",instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Participants per server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(4, sum by (instance) (bbb_meetings_participants{target_type=~\"$kind\",instance=~\"$instance\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Rooms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Rooms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (bbb_room_participants_gcount{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Participants by Client Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "sum(bbb_meetings_participant_clients{target_type=\"bigbluebutton\",instance=~\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Max Participants for Selected Timeframe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(4, sum by (instance) (bbb_meetings_participants{target_type=~\"$kind\",instance=~\"$instance\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utlization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utlization [%]" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\",job=\"bigbluebutton\"}[5m])) by (instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\",job=\"bigbluebutton\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\",job=\"bigbluebutton\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Recordings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Recordings Processing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (bbb_recordings_processing{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recordings Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (bbb_recordings_published{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recordings Unpublished",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (bbb_recordings_unpublished{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recordings Deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (bbb_recordings_deleted{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Heatmaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Heatmap of Room Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_participants_bucket{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Listeners Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of listeners while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_listeners_bucket{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Voice Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of voice participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_voice_participants_bucket{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Video Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of video participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by (le) (bbb_room_video_participants_bucket{target_type=~\"$kind\",instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Metrics Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{target_type=~\"$kind\",instance=~\"$instance\"}[5m])) by (le, instance, endpoint, parameters))) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API 95-th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "Latency [s]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{target_type=~\"$kind\",instance=~\"$instance\",endpoint=\"getMeetings\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getMeetings"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{target_type=~\"$kind\",instance=~\"$instance\",endpoint=\"getRecordings\",parameters=\"state=processing\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{target_type=~\"$kind\",instance=~\"$instance\",endpoint=\"getRecordings\",parameters=\"state=processed\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings processed"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{target_type=~\"$kind\",instance=~\"$instance\",endpoint=\"getRecordings\",parameters=\"state=published\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings published"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{target_type=~\"$kind\",instance=~\"$instance\",endpoint=\"getRecordings\",parameters=\"state=unpublished\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings unpublished"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{instance=~\"$instance\",endpoint=\"getRecordings\",parameters=\"state=deleted\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}} - getRecordings deleted"
    }
   ]
  }
 ]
}