{
 "title": "DockerEngine",
 "description": "Docker Engine metrics overview.",
 "tags": [
  "docker",
  "docker-ce",
  "docker-engine",
  "docker-metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(engine_daemon_engine_info,instance)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "engine_daemon_engine_cpus_cpus{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Actions Percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actions Percentiles $instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(engine_daemon_container_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "{{ action }} 99"
      },
      {
       "expr": "histogram_quantile(0.90, rate(engine_daemon_container_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "{{ action }} 90"
      },
      {
       "expr": "histogram_quantile(0.50, rate(engine_daemon_container_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "{{ action }}50"
      },
      {
       "expr": "histogram_quantile(0.25, rate(engine_daemon_container_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "{{ action }} 25"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Container Actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total $instance Actions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "engine_daemon_container_actions_seconds_count{instance=~\"$instance\"}",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Actions Percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(engine_daemon_network_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "{{ action }} 99"
      },
      {
       "expr": "histogram_quantile(0.90, rate(engine_daemon_network_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "{{ action }} 90"
      },
      {
       "expr": "histogram_quantile(0.50, rate(engine_daemon_network_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "{{ action }} 50"
      },
      {
       "expr": "histogram_quantile(0.25, rate(engine_daemon_network_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "{{ action }} 25"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Network Actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance Network Actions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "engine_daemon_network_actions_seconds_count{instance=~\"$instance\"}",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Subscribers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "engine_daemon_events_subscribers_total{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Builds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "builder_builds_triggered_total{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Failed Builds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (builder_builds_failed_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Etcd Disk Wal Duration Percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "50"
      },
      {
       "expr": "histogram_quantile(0.25, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\"}[$interval]))",
       "legendFormat": "25"
      }
     ]
    }
   ]
  }
 ]
}