{
 "title": "ElasticSearch",
 "description": "ElasticSearch metrics overview.",
 "tags": [
  "cluster",
  "database",
  "elasticsearch",
  "logging",
  "nosgbd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "ElasticSearch Cluster",
    "query": "label_values(elasticsearch_indices_docs,cluster)"
   },
   {
    "name": "instance",
    "label": "ElasticSearch Node",
    "query": "label_values(elasticsearch_indices_docs{cluster=~\"$cluster\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Green",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (instance) (elasticsearch_cluster_health_status{instance=~\"$instance\",color=\"green\"} == 1) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Yellow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (instance) (elasticsearch_cluster_health_status{instance=~\"$instance\",color=\"yellow\"} == 1) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Red",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (instance) (elasticsearch_cluster_health_status{instance=~\"$instance\",color=\"red\"} == 1) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(elasticsearch_breakers_tripped{instance=~\"$instance\",cluster=~\"$cluster\"} > 0)"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_process_cpu_percent{instance=~\"$instance\",cluster=~\"$cluster\"}) / count(elasticsearch_process_cpu_percent{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{instance=~\"$instance\",cluster=~\"$cluster\"}) / sum (elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_data_nodes{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_pending_tasks{instance=~\"$instance\",cluster=~\"$cluster\"}) / count(elasticsearch_cluster_health_number_of_nodes{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_process_open_files_count{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active primary shards",
   "type": "singlestat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_active_primary_shards{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "singlestat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_active_shards{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "singlestat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_initializing_shards{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "singlestat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_relocating_shards{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Delayed shards",
   "type": "singlestat",
   "description": "Shards delayed to reduce reallocation overhead",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_delayed_unassigned_shards{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "singlestat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_unassigned_shards{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(elasticsearch_jvm_gc_collection_seconds_count{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(elasticsearch_jvm_gc_collection_seconds_sum{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Translog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total translog operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_translog_operations{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total translog size in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_translog_size_in_bytes{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tripped for breakers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,breaker) (elasticsearch_breakers_tripped{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{breaker}}"
      }
     ]
    },
    {
     "title": "Estimated size in bytes of breaker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,breaker) (elasticsearch_breakers_estimated_size_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{breaker}} estimated size"
      },
      {
       "expr": "sum by (instance,breaker) (elasticsearch_breakers_limit_size_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{breaker}} limit"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load average",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (elasticsearch_os_load1{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} load1"
      },
      {
       "expr": "sum by (instance) (elasticsearch_os_load5{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} load5"
      },
      {
       "expr": "sum by (instance) (elasticsearch_os_load15{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} load15"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "percent", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (elasticsearch_process_cpu_percent{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM memory usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,area) (elasticsearch_jvm_memory_used_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{area}} Used"
      },
      {
       "expr": "sum by (instance,area) (elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{area}} Max"
      },
      {
       "expr": "sum by (instance,pool) (elasticsearch_jvm_memory_pool_peak_used_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} peak used in pool {{pool}}"
      }
     ]
    },
    {
     "title": "JVM memory committed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,area) (elasticsearch_jvm_memory_committed_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{area}} Comitted"
      },
      {
       "expr": "sum by (instance,area) (elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{area}} Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit", "label": "Disk Usage %" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,path) (1 - (elasticsearch_filesystem_data_available_bytes{instance=~\"$instance\",cluster=~\"$cluster\"} / elasticsearch_filesystem_data_size_bytes{instance=~\"$instance\",cluster=~\"$cluster\"}))",
       "legendFormat": "{{instance}} {{path}}"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/sec" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_transport_tx_size_bytes_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} sent"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_transport_rx_size_bytes_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} received"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents count on node",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (elasticsearch_indices_docs{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Documents indexed rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "index calls/s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Documents deleted rate",
     "type": "graph",
     "description": "Count of deleted documents on this node",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_docs_deleted{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Documents merged rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_merges_docs_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Documents merged bytes",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_merges_total_size_bytes_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Indexing time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Merging time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_merges_total_time_seconds_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Throttle time for index store",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_store_throttle_time_seconds_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Operations stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Operations  rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} indexing"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} query"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_search_fetch_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} fetch"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_merges_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} merges"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_refresh_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} refresh"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_flush_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} flush"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_get_exists_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} get exists"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_get_missing_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} get missing"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_get_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} get"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_indexing_delete_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} indexing_delete"
      }
     ]
    },
    {
     "title": "Total Operations time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} indexing"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} query"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} fetch"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_merges_total_time_seconds_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} merges"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_refresh_time_seconds_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} refresh"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_flush_time_seconds{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} flush"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_get_exists_time_seconds{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} get_exists"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_get_time_seconds{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} get_time"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_get_missing_time_seconds{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} get_missing"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_indexing_delete_time_seconds_total{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} indexing_delete"
      },
      {
       "expr": "sum by (instance) (irate(elasticsearch_indices_get_time_seconds{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} get"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool operations rejected",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(elasticsearch_thread_pool_rejected_count{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Thread Pool operations queued",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,type) (elasticsearch_thread_pool_active_count{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{type}}"
      }
     ]
    },
    {
     "title": "Thread Pool threads active",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,type) (elasticsearch_thread_pool_active_count{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{type}}"
      }
     ]
    },
    {
     "title": "Thread Pool operations completed",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,type) (irate(elasticsearch_thread_pool_completed_count{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Field data memory size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (elasticsearch_indices_fielddata_memory_size_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Field data evictions",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(elasticsearch_indices_fielddata_evictions{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "bytes", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (elasticsearch_indices_query_cache_memory_size_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(elasticsearch_indices_query_cache_evictions{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Evictions from filter cache",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(elasticsearch_indices_filter_cache_evictions{instance=~\"$instance\",cluster=~\"$cluster\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of index segments",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (elasticsearch_indices_segments_count{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current memory size of segments in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (elasticsearch_indices_segments_memory_bytes{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of documents with only primary shards",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_docs_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with only primary shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with all shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_store_size_bytes_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Index writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index writer with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_index_writer_memory_bytes_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Index writer with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_index_writer_memory_bytes_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segments with only primary shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_count_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Segments with all shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_count_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Size of segments with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_memory_bytes_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Size of segments with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_memory_bytes_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Doc values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Doc values with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_doc_values_memory_bytes_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Doc values with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_doc_values_memory_bytes_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Fields",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of fields with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_fields_memory_bytes_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Size of fields with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_fields_memory_bytes_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Fixed bit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of fixed bit with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_fixed_bit_set_memory_bytes_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Size of fixed bit with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_fixed_bit_set_memory_bytes_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Norms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of norms with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_norms_memory_bytes_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Size of norms with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_norms_memory_bytes_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Points",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of points with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_points_memory_bytes_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Size of points with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_points_memory_bytes_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Terms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of terms with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_terms_memory_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Number of terms with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_terms_memory_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Version map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of version map with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_version_map_memory_bytes_primary{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    },
    {
     "title": "Size of version map with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,index) (elasticsearch_indices_segment_version_map_memory_bytes_total{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{index}}"
      }
     ]
    }
   ]
  }
 ]
}