{
 "title": "FreeSwitch",
 "description": "FreeSwitch metrics overview.",
 "tags": [
  "Application",
  "FreeSwitch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "FreeSwitch Server",
    "query": "label_values(freeswitch_up,instance)"
   },
   {
    "name": "interval",
    "label": "Rates Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "FreeSwitch Sessions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (freeswitch_session_limit{instance=~\"$instance\"})",
     "legendFormat": "Total {{instance}}"
    },
    {
     "expr": "sum by (instance) (freeswitch_session_active{instance=~\"$instance\"})",
     "legendFormat": "Active {{instance}}"
    }
   ]
  },
  {
   "title": "Actives",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(freeswitch_up{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "FreeSwitch New Sessions per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (increase(freeswitch_session_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(freeswitch_up{instance=~\"$instance\"}) - sum(freeswitch_up{instance=~\"$instance\"})"
    }
   ]
  }
 ]
}