{
 "title": "Go Applications",
 "description": "Go metrics overview.",
 "tags": [
  "Application",
  "Go"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(go_memstats_alloc_bytes,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} resident"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (go_memstats_alloc_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} bytes allocated"
    },
    {
     "expr": "sum by (instance) (rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}} alloc rate"
    },
    {
     "expr": "sum by (instance) (go_memstats_stack_inuse_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} stack inuse"
    },
    {
     "expr": "sum by (instance) (go_memstats_heap_inuse_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (process_open_fds{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (go_goroutines{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,quantile) (go_gc_duration_seconds{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} {{quantile}}"
    }
   ]
  }
 ]
}