{
 "title": "Grafana",
 "description": "Grafana metrics overview.",
 "tags": [
  "Application",
  "Go",
  "Grafana",
  "Monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Grafana Server",
    "query": "label_values(grafana_build_info,instance)"
   }
  ]
 },
 "panels": [
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time (last)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-max(process_start_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Dashboards Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (sum by (instance) (grafana_stat_totals_dashboard{instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Organisations Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(grafana_stat_total_orgs{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Users Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (sum by (instance) (grafana_stat_total_users{instance=~\"$instance\"}))"
    }
   ]
  },
  { "title": "Responce Codes and Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Grafana Accesses in $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grafana_api_response_status_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} API {{code}}"
    },
    {
     "expr": "increase(grafana_page_response_status_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} Page {{code}}"
    },
    {
     "expr": "increase(grafana_proxy_response_status_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} Proxy {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Req/Resp by $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} {{method}} {{handler}} {{statuscode}}"
    }
   ]
  },
  {
   "title": "Logins by $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grafana_api_login_post_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} POST"
    },
    {
     "expr": "increase(grafana_api_login_oauth_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} OAuth"
    }
   ]
  },
  { "title": "Dataproxy Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Dataproxy Request Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=~\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "{{instance}} 0.5 "
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}} 0.9"
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{instance}} 0.99"
    }
   ]
  },
  {
   "title": "Dataproxy Request Duration by $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dataproxy_request_all_milliseconds_sum{instance=~\"$instance\"}[$interval]) / rate(grafana_api_dataproxy_request_all_milliseconds_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dashboard Get Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Dashboard Get Duration Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds{instance=~\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "{{instance}} 0.5"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}} 0.9"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{instance}} 0.99"
    }
   ]
  },
  {
   "title": "Average Dashboard Get Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds_sum{instance=~\"$instance\"} / grafana_api_dashboard_get_milliseconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dashboard Save Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Dashboard Save Duration Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds{instance=~\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "{{instance}} 0.5"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}} 0.9"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{instance}} 0.99"
    }
   ]
  },
  {
   "title": "Average Dashboard Save Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds_sum{instance=~\"$instance\"} / grafana_api_dashboard_save_milliseconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dashboard Search Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Dashboard Search Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard search duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds{instance=~\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "{{instance}} 0.5"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "{{instance}} 0.9"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{instance}} 0.99"
    }
   ]
  },
  {
   "title": "Average Dashboard Search Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds_sum{instance=~\"$instance\"}/grafana_api_dashboard_search_milliseconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}