{
 "title": "Kibana",
 "description": "Kibana metrics overview.",
 "tags": [
  "application",
  "elasticsearch",
  "logging"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kibana_status,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kibana Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kibana_status{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Elasticsearch Plugin Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kibana_plugin_elasticsearch{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Kibana Prometheus Exporter Plugin Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kibana_plugin_kibanaPrometheusExporter{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Kibana Machine Learning Plugin Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kibana_plugin_ml{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kibana_concurrent_connections{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Min Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kibana_millis_uptime{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Overall Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (100 * kibana_heap_used_in_bytes{instance=~\"$instance\"} / kibana_heap_max_in_bytes{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kibana_concurrent_connections{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kibana_os_load1{instance=~\"$instance\"}",
     "legendFormat": "Load 1m {{instance}}"
    },
    {
     "expr": "kibana_os_load5{instance=~\"$instance\"}",
     "legendFormat": "Load 5m {{instance}}"
    },
    {
     "expr": "kibana_os_load15{instance=~\"$instance\"}",
     "legendFormat": "Load 15m {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kibana_heap_used_in_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Heap Used"
    },
    {
     "expr": "kibana_heap_max_in_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Heap Max"
    }
   ]
  }
 ]
}