{
 "title": "MongoDB WiredTiger",
 "description": "MongoDB WiredTiger storage engine metrics overview.",
 "tags": [
  "Database",
  "MongoDB"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "MongoDB Server",
    "query": "label_values(mongodb_mongod_storage_engine,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "WiredTiger Cache Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(mongodb_mongod_wiredtiger_cache_bytes{instance=~\"$instance\",type=\"total\"}[5m]))"
    }
   ]
  },
  {
   "title": "WiredTiger Max Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(mongodb_mongod_wiredtiger_cache_max_bytes{instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Cached (on nodes)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_Cached_bytes{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Available (on nodes)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) ((node_memory_MemAvailable_bytes{instance=~\"$instance\"}) or sum by (instance) ((node_memory_MemFree_bytes{instance=~\"$instance\"} + node_memory_Buffers_bytes{instance=~\"$instance\"} + node_memory_Cached_bytes{instance=~\"$instance\"})) / node_memory_MemTotal_bytes{instance=~\"$instance\"} * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WiredTiger Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,type) (rate(mongodb_mongod_wiredtiger_transactions_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=~\"$instance\",type=\"read\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=~\"$instance\",type=\"read\"}[5m]))",
     "legendFormat": "{{instance}} Read"
    },
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=~\"$instance\",type=\"written\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=~\"$instance\",type=\"written\"}[5m]))",
     "legendFormat": "{{instance}} Written"
    }
   ]
  },
  {
   "title": "WiredTiger Block Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (mongodb_mongod_wiredtiger_session_open_cursors_total{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} Cursors"
    },
    {
     "expr": "sum by (instance) (mongodb_mongod_wiredtiger_session_open_sessions_total{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} Sessions"
    }
   ]
  },
  {
   "title": "WiredTiger Concurrency Tickets Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{instance=~\"$instance\"} -mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (mongodb_mongod_global_lock_current_queue{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Checkpoint Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} current"
    },
    {
     "expr": "sum by (instance,type) (mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Eviction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Pages / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, type) (rate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (mongodb_mongod_wiredtiger_cache_max_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} Max"
    },
    {
     "expr": "sum by (instance) (mongodb_mongod_wiredtiger_cache_bytes{instance=~\"$instance\",type=\"total\"})",
     "legendFormat": "{{instance}} Used"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (mongodb_mongod_wiredtiger_cache_pages{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, type) (rate(mongodb_mongod_wiredtiger_log_operations_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_operations_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, type) (rate(mongodb_mongod_wiredtiger_log_bytes_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_bytes_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_wiredtiger_log_records_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_records_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,state) (rate(mongodb_mongod_metrics_document_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{state}}"
    },
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_op_counters_repl_total{instance=~\"$instance\",type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$instance\",type=\"delete\"}[5m]))",
     "legendFormat": "{{instance}} repl_deleted"
    },
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_op_counters_repl_total{instance=~\"$instance\",type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$instance\",type=\"update\"}[5m]))",
     "legendFormat": "{{instance}} repl_updated"
    },
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_op_counters_repl_total{instance=~\"$instance\",type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$instance\",type=\"insert\"}[5m]))",
     "legendFormat": "{{instance}} repl_inserted"
    },
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} ttl_deleted"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, state) (rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{state}}"
    },
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_metrics_record_moves_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_extra_info_page_faults_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{instance=~\"$instance\"}[5m]) or rate(mongodb_extra_info_page_faults_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} Faults"
    }
   ]
  }
 ]
}