{
 "title": "MongoDB Overview",
 "description": "MongoDB metrics overview.",
 "tags": [
  "Database",
  "MongoDB"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "MongoDB Server",
    "query": "label_values(mongodb_connections,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,type) (rate(mongodb_op_counters_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,state) (rate(mongodb_mongod_metrics_document_total{instance=~\"$instance\"}[$interval]))  ",
     "legendFormat": "{{instance}} {{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,state) (rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}} {{state}}"
    }
   ]
  },
  {
   "title": "Replica Set Metrics for $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "env"
  },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (mongodb_mongod_replset_number_of_members{instance=~\"$instance\"})",
     "legendFormat": "# members"
    },
    {
     "expr": "sum by (instance) (mongodb_mongod_replset_member_health{instance=~\"$instance\"} == 1)",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "graph",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,state,name) (mongodb_mongod_replset_member_state{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} {{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,type) (rate(mongodb_op_counters_repl_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  { "title": "Health metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mongodb_instance_uptime_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mongodb_connections{instance=~\"$instance\",state=\"available\"})"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mongodb_connections{instance=~\"$instance\",state=\"current\"})"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,type) (mongodb_mongod_replset_oplog_size_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,type) (mongodb_memory{instance=~\"$instance\",type=~\"resident|virtual\"})",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,state) (rate(mongodb_network_bytes_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}} {{state}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Oplog Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_replset_oplog_head_timestamp{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,device) ((rate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[$interval]) / 1000 or irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[$interval]) / 1000))",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Reads Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,device) (rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,device) (rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  }
 ]
}