{
 "title": "MongoDB Operations",
 "description": "MongoDB operations overview.",
 "tags": [
  "Database",
  "MongoDB"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Replica Set",
    "query": "label_values(mongodb_mongod_replset_date,set)"
   },
   {
    "name": "instance",
    "label": "MongoDB Server",
    "query": "label_values(mongodb_mongod_replset_date{set=~\"$cluster\",},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Command Operations",
   "type": "graph",
   "description": "Shows how many times a command is executed per second on average during the selected interval.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,set,type) (rate(mongodb_mongod_op_counters_total{instance=~\"$instance\",set=~\"$cluster\",type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{instance=~\"$instance\",set=~\"$cluster\",type!=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{instance=~\"$instance\",set=~\"$cluster\",type!=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{instance=~\"$instance\",set=~\"$cluster\",type!=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{instance=~\"$instance\",set=~\"$cluster\",type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{instance=~\"$instance\",set=~\"$cluster\",type!=\"command\"}[5m]))",
     "legendFormat": "{{instance}} {{set}} {{type}}"
    },
    {
     "expr": "sum by (instance,type) (rate(mongodb_mongod_op_counters_repl_total{instance=~\"$instance\",set=~\"$cluster\",type!~\"(command|query|getmore)\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$instance\",set=~\"$cluster\",type!~\"(command|query|getmore)\"}[5m]) or rate(mongodb_mongos_op_counters_repl_total{instance=~\"$instance\",set=~\"$cluster\",type!~\"(command|query|getmore)\"}[$interval]) or irate(mongodb_mongos_op_counters_repl_total{instance=~\"$instance\",set=~\"$cluster\",type!~\"(command|query|getmore)\"}[5m]) or rate(mongodb_op_counters_repl_total{instance=~\"$instance\",set=~\"$cluster\",type!~\"(command|query|getmore)\"}[$interval]) or irate(mongodb_op_counters_repl_total{instance=~\"$instance\",set=~\"$cluster\",type!~\"(command|query|getmore)\"}[5m]))",
     "legendFormat": "{{instance}} repl_{{type}}"
    },
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$instance\"}[5m]) or rate(mongodb_mongos_metrics_ttl_deleted_documents_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongos_metrics_ttl_deleted_documents_total{instance=~\"$instance\"}[5m]) or rate(mongodb_metrics_ttl_deleted_documents_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_metrics_ttl_deleted_documents_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ttl_delete"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Keep in mind the hard limit on the maximum number of connections set by your distribution.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (mongodb_mongod_connections{instance=~\"$instance\",state=\"current\"} or\nmongodb_mongos_connections{instance=~\"$instance\",state=\"current\"} or mongodb_connections{instance=~\"$instance\",state=\"current\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "graph",
   "description": "Helps identify why connections are increasing. Shows active cursors compared to cursors being automatically killed after 10 minutes due to an application not closing the connection.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,state) (mongodb_mongod_metrics_cursor_open{instance=~\"$instance\"} or mongodb_mongod_cursors{instance=~\"$instance\"} or mongodb_mongos_metrics_cursor_open{instance=~\"$instance\"} or mongodb_mongos_cursors{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} {{state}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "description": "When used in combination with 'Command Operations', this graph can help identify write amplification. For example, when one insert or update command actually inserts or updates hundreds, thousands, or even millions of documents.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,state) (rate(mongodb_mongod_metrics_document_total{instance=~\"$instance\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{state}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "description": "Any number of queued operations for long periods of time is an indication of possible issues. Find the cause and fix it before requests get stuck in the queue.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,type) (mongodb_mongod_global_lock_current_queue{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Query Efficiency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_metrics_document_total{instance=~\"$instance\",state=\"returned\"}[$interval])) / sum by (instance) (rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\",state=\"scanned_objects\"}[$interval])) or sum by (instance) (irate(mongodb_mongod_metrics_document_total{instance=~\"$instance\",state=\"returned\"}[5m])) /\nsum by (instance) (irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\",state=\"scanned_objects\"}[5m]))",
     "legendFormat": "{{instance}} Document"
    },
    {
     "expr": "(sum by (instance) (rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\",state=\"scanned\"}[$interval])) /\nsum by (instance) (rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\",state=\"scanned_objects\"}[$interval])) or sum by (instance) (irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\",state=\"scanned\"}[5m])) /\nsum by (instance) (irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\",state=\"scanned_objects\"}[5m])))",
     "legendFormat": "{{instance}} Index"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,state) (rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{state}}"
    },
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_metrics_record_moves_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} moved"
    }
   ]
  },
  {
   "title": "getLastError Write Time",
   "type": "graph",
   "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongod_metrics_get_last_error_wtime_total_milliseconds{instance=~\"$instance\"}[$interval]) or \nirate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{instance=~\"$instance\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{instance=~\"$instance\"}[$interval]) or \nirate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} Write Wait Time"
    }
   ]
  },
  {
   "title": "getLastError Write Operations",
   "type": "graph",
   "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_metrics_get_last_error_wtime_num_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_metrics_get_last_error_wtime_num_total{instance=~\"$instance\"}[5m]) or rate(mongodb_mongos_metrics_get_last_error_wtime_num_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongos_metrics_get_last_error_wtime_num_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} Total"
    },
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{instance=~\"$instance\"}[5m]) or rate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{instance=~\"$instance\"}[5m])) ",
     "legendFormat": "{{instance}} Timeouts"
    }
   ]
  },
  {
   "title": "Assert Events",
   "type": "graph",
   "description": "Asserts are not important by themselves, but you can correlate spikes with other graphs.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,type) (rate(mongodb_mongod_asserts_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_asserts_total{instance=~\"$instance\"}[5m]) or rate(mongodb_mongos_asserts_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongos_asserts_total{instance=~\"$instance\"}[5m]) or rate(mongodb_asserts_total{instance=~\"$instance\"}[$interval]) or \nirate(mongodb_asserts_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "description": "Page faults indicate that requests are processed from disk either because an index is missing or there is not enough memory for the data set. Consider increasing memory or sharding out.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(mongodb_mongod_extra_info_page_faults_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{instance=~\"$instance\"}[5m]) or rate(mongodb_mongos_extra_info_page_faults_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_mongos_extra_info_page_faults_total{instance=~\"$instance\"}[5m]) or rate(mongodb_extra_info_page_faults_total{instance=~\"$instance\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}Faults"
    }
   ]
  }
 ]
}