{
 "title": "NodeJS Metrics",
 "description": "Node.JS Runtime metrics overview.",
 "tags": [
  "application",
  "nodejs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nodejs_heap_space_size_available_bytes,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Nodejs Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "repeat": "service",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "bottomk(1,sum(nodejs_version_info{instance=~\"$instance\"}) by (version))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_requests{instance=~\"$instance\"}",
     "legendFormat": "Active {{type}} {{instance}})"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Total {{instance}})"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles{instance=~\"$instance\"}",
     "legendFormat": "Active {{type}} {{instance}})"
    },
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Total {{instance}})"
    }
   ]
  },
  {
   "title": "Service Process Heap (max)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "repeat": "service",
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(process_heap_bytes{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Process Restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Service Max file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "repeat": "service",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_max_fds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Service Metrics scrape duration sum",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "repeat": "service",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(scrape_duration_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} User"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} System"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Event Loop Lag"
    }
   ]
  },
  {
   "title": "Maximum Opened file descriptors",
   "type": "singlestat",
   "description": "Given collected process opened fds , returns the maximum value",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "repeat": "service",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_open_fds{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "External Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} External Memory"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Used"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Resident"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Virtual"
    }
   ]
  },
  { "title": "Heap Space Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{space}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{space}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{space}}"
    }
   ]
  }
 ]
}