- name: Installs LDAP Commons
  apt:
    name: ldap-utils
    state: present
- name: Ensures LDAP Configuration Directory Exists
  file:
    dest: /etc/ldap
    group: root
    mode: 0755
    owner: root
    state: directory
- name: Installs ldap.conf
  template:
    dest: /etc/ldap/ldap.conf
    group: root
    mode: 0644
    owner: root
    src: ldap.j2
