# https://docs.bigbluebutton.org/legacy/11install.html#check-server-specs
- name: Installs Locales
  apt:
    name:
    - locales
    - locales-all
    state: present
- name: Configures Locales Generation
  lineinfile:
    dest: /etc/locale.gen
    regexp: "^{{ localegen }}"
    line: "{{ localegen }}"
  register: regen_locales
- name: Ensures locale.alias Present
  changed_when: False
  file:
    dest: /usr/share/locale/locale.alias
    src: /etc/locale.alias
    state: link
- name: Generates Locales
  command: locale-gen
  when:
  - regen_locales is defined
  - regen_locales is changed
- name: Sets LANG
  lineinfile:
    dest: /etc/default/locale
    line: "export LANG={{ locale }}"
    regexp: "^export LANG="
- name: Sets LANGUAGE
  lineinfile:
    dest: /etc/default/locale
    line: "export LANGUAGE={{ lang }}"
    regexp: "^export LANGUAGE="
- name: Sets LANG
  lineinfile:
    dest: /etc/default/locale
    line: export LC_ALL=C
    regexp: "^export LC_ALL="
