- include_tasks: rootfs.yaml
- include_tasks: commons.yaml
- include_tasks: certs-trusted.yaml
- include_tasks: locale.yaml
  when:
  - ansible_distribution in [ 'Debian', 'Devuan', 'Ubuntu' ]
- include_tasks: time.yaml
- include_tasks: ipa.yaml
  when:
  - groups['freeipa'] | length > 0
  - ansible_fqdn not in groups['freeipa']
  - ansible_hostname not in groups['freeipa']
  - ansible_nodename not in groups['freeipa']
- include_tasks: update.yaml
- include_tasks: prometheus.yaml
  when:
  - >
      groups['prometheus'] | length > 0
      or do_prometheus | default(False)
