- name: Installs x509 Certificates TTL Probe Script
  copy:
    dest: /usr/local/sbin/certificates-prometheus
    group: root
    mode: 0755
    owner: root
    src: prometheus-check_certificates.sh
- name: Installs x509 Certificates TTL Probe Service
  copy:
    dest: "/etc/systemd/system/certificates-prometheus.{{ item }}"
    group: root
    mode: 0644
    owner: root
    src: "prometheus-check_certificates.{{ item }}"
  loop:
  - service
  - timer
  register: punit
- name: Reloads Systemd Configuration
  shell: systemctl daemon-reload
  when:
  - punit is defined
  - punit is changed
- name: Enables x509 Certificates TTL Prometheus Collection Job
  service:
    enabled: yes
    name: certificates-prometheus.timer
    state: started
