- block:
  - name: Creates Swap File
    args:
      creates: /swapfile
    command: |
      dd if=/dev/zero of=/swapfile bs=1M count={{ swap_size | default(1024) }}
    register: swcreated
  - name: Sets Proper Permissions on Swap File
    file:
      dest: /swapfile
      group: root
      mode: 0600
      owner: root
  - name: Makes Swap Filesystem
    command: mkswap /swapfile
    when:
    - swcreated is defined
    - swcreated is changed
  - name: Adds Swap Entry to /etc/fstab
    lineinfile:
      dest: /etc/fstab
      line: /swapfile none swap sw 0 0
    register: swconf
  - name: Mounts Swap Devices
    command: swapon -a
    when:
    - swconf is defined
    - swconf is changed
  when:
  - (ansible_swaptotal_mb | int) == 0
