- block:
  - name: Creates Swap File
    command: "dd if=/dev/zero of=/swapfile bs=1M count={{ swap_size | default(1024) }}"
  - name: Sets Proper Permissions on Swap File
    file:
      dest: /swapfile
      group: root
      mode: 0600
      owner: root
  - name: Makes Swap Filesystem
    command: mkswap /swapfile
  - name: Adds Swap Entry to /etc/fstab
    lineinfile:
      dest: /etc/fstab
      line: /swapfile none swap sw 0 0
  - name: Mounts Swap Devices
    command: swapon -a
  when:
  - (ansible_swapfree_mb | int) == 0
