- name: Checks for Ansible Mark
  register: was_provisioned
  stat:
    path: /root/.ansible/bbb-mark
- block:
  - name: Upgrades System (deb)
    apt:
      upgrade: dist
    register: sysupgrade
    when:
    - ansible_distribution in [ 'Debian', 'Devuan', 'Ubuntu' ]
  - name: Upgrades System (rhel)
    register: sysupgradetoo
    yum:
      name: '*'
      state: latest
    when:
    - ansible_distribution in [ 'CentOS', 'Fedora', 'RedHat' ]
  - name: Marks Up-to-Date
    args:
      chdir: /root/.ansible
    shell: date >bbb-mark
  - block:
    - name: Reboots System
      shell: ( sleep 2 && reboot ) &
    - name: Waits for System to Reboot
      wait_for_connection:
        delay: 10
    when:
    - >
        (sysupgradetoo is defined
         and sysupgradetoo is changed)
        or (sysupgrade is defined
            and sysupgrade is changed)
  when:
  - was_provisioned is defined
  - was_provisioned.stat is defined
  - not was_provisioned.stat.exists
