- name: Installs Kibana Persisting Directory
  file:
    dest: /usr/share/kibana
    group: root
    mode: 0755
    owner: root
    state: directory
- name: Installs Kibana Plugins Directory
  file:
    dest: /usr/share/kibana/plugins
    group: 1000
    mode: 0755
    owner: 1000
    state: directory
- include_role:
    name: docker
    tasks_from: check-pull.yaml
  vars:
    image_tag: "{{ kibana_images_release }}"
    image_url: "{{ kibana_images_repo }}"
