#greenlight_fqdn: {{ ansible_fqdn }}

bigbluebutton_letsencrypt_address: r00t@example.com

bigbluebutton_exporter_images_repo: greenstatic/bigbluebutton-exporter
bigbluebutton_exporter_images_release: v0.6.0
bigbluebutton_exporter_port: 9688

bigbluebutton_recordings_retention_days: 7

freeswitch_exporter_port: 9725
freeswitch_exporter_release: 1.0.1

#freeswitch_trunk_dids:
#- 0033xxxxxx
#- 0033xxxxxy
#- 0033xxxxxz
freeswitch_trunk_expire: 1800
freeswitch_trunk_name: trunk-ovh
#freeswitch_trunk_password: secret
freeswitch_trunk_proxy: siptrunk.ovh.net
freeswitch_trunk_realm: siptrunk.ovh.net
freeswitch_trunk_register: "true"
#freeswitch_trunk_username: 0033xxxxxx

kurento_exporter_port: 9148

turn_default_plain_port: 3478
turn_default_tls_port: 443
