firehol_app_opened_ports:
- name: ssh
  value: tcp/22
- name: prometheus
  value: tcp/9090
- name: nodexp
  value: tcp/9142
- name: nginxxp
  value: tcp/9143
- name: nginxluaxp
  value: tcp/9145
- name: systemdxp
  value: tcp/9147
