#!/bin/sh
# minimalistic BigBlueButton CLI
# pending completion ...

if test "$DEBUG"; then
    set -x
fi
if ! test -r /etc/bbb-cli/api.conf; then
    echo Failed loading bbb-cli configuration >&2
    exit 1
fi
. /etc/bbb-cli/api.conf

getCheckSum()
{
    if test -z "$CMD" -o -z "$CALL" -z -o "$SECRET"; then
	echo missing input &2
	exit 1
    fi
    CKSTR="$CMD$CALL$SECRET"
    echo -n "$CKSTR" | shasum | awk '{print $1}'
}

usage()
{
    cat <<EOF
  usage: bbb-cli <command> [arguments]
       bbb-cli create-room room-name meeting-uid
       bbb-cli delete-recording <recording-id>
       bbb-cli get-deleted-recordings
       bbb-cli get-processing-recordings
       bbb-cli get-published-recordings
       bbb-cli get-recordings [state]
       bbb-cli get-room meeting-uid
       bbb-cli get-rooms
       bbb-cli get-unpublished-recordings
       bbb-cli help
EOF
}

case "$1" in
    create-room)
	CALL="name=$2&meetingID=$3&isBreakout=false"
	CMD=create
	shift 2
	;;
    delete-recording)
	if test "$2"; then
	    CALL=recordID=$2
	    CMD=deleteRecordings
	    shift
	else
	    echo ERROR: missing recording ID
	    echo see bbb-cli get-recordings for a list of recordings
	fi >&2
	;;
    get-deleted-recordings)
        CALL=state=deleted
        CMD=getRecordings
        ;;
    get-processing-recordings)
        CALL=state=processing
        CMD=getRecordings
        ;;
    get-published-recordings)
        CALL=state=published
        CMD=getRecordings
        ;;
    get-recordings)
        check=published
        if test "$2"; then
            check=$2
        fi
        CALL=state=$check
        CMD=getRecordings
	shift
        ;;
    get-rooms)
	CALL=
	CMD=getMeetings
	;;
    get-room)
	CALL="meetingID=$2"
	CMD=getMeetingInfo
	shift
	;;
    get-unpublished-recordings)
        CALL=state=unpublished
        CMD=getRecordings
        ;;
    help|--help|-h)
	usage
	exit 0
	;;
    *)
	echo args error >&2
	usage >&2
	exit 1
	;;
esac

if test -z "$CMD"; then
    exit 1
fi

CKSUM=`getCheckSum 2>/dev/null`
if test -z "$CKSUM"; then
    echo failed generating checksum >&2
    exit 1
fi

curl -vvv "$HOST/$CMD?$CALL&checksum=$CKSUM"

exit $?
