do_redis_backups: False
firehol_app_filtered_ports:
- name: ssh
  value: tcp/22
- name: redis
  value: tcp/6379
- name: mongodbxp
  value: tcp/9117
- name: nodexp
  value: tcp/9142
- name: nginxxp
  value: tcp/9143
- name: nginxluaxp
  value: tcp/9145
- name: systemdxp
  value: tcp/9147
- name: redisxp
  value: tcp/9179
- name: mongodb
  value: tcp/27017
firehol_app_opened_ports:
- name: http
  value: tcp/80
- name: https
  value: tcp/443
- name: media
  value: udp/16384:32768
firehol_opened_ports: []

unattended_upgrades_blacklist:
- bbb-apps
- bbb-apps-akka
- bbb-apps-screenshare
- bbb-apps-sip
- bbb-apps-video
- bbb-apps-video-broadcast
- bbb-client
- bbb-config
- bbb-etherpad
- bbb-freeswitch-core
- bbb-freeswitch-sounds
- bbb-fsesl-akka
- bbb-html5
- bbb-mkclean
- bbb-playback-presentation
- bbb-record-core
- bbb-red5
- bbb-transcode-akka
- bbb-web
- bbb-webrtc-sfu
- bigbluebutton
- ffmpeg
- libavcodec
- libavdevice
- libavfilter
- libavformat
- libavresample
- libavutil
- libopusenc
- libpostproc
- libswresample
- libswscale
- mongodb-org
- mongodb-org-mongos
- mongodb-org-server
- mongodb-org-shell
- mongodb-org-tools
- nodejs
- redis-server
- redis-tools
