- name: Ensures BigBlueButton Home Directory Exists
  file:
    dest: /home/bigbluebutton
    force: no
    group: bigbluebutton
    mode: 0700
    owner: bigbluebutton
    state: directory
  register: fixed_home

- name: Installs BigBlueButton Demo
  apt:
    name: bbb-demo
    state: present
  register: has_demo
  when:
  - groups['scalelite'] | length == 0
  - groups['greenlight'] | length == 0

- name: Installs BigBlueButton WebHoooks
  apt:
    name: bbb-webhooks
    state: present
  when:
  - >
      groups['rocketchat'] | length > 0
      or do_bbb_webhooks | default(False)

- block:
  - name: Installs BigBlueButton/Scalelite Recordings Post Process Configuration
    template:
      dest: /usr/local/bigbluebutton/core/scripts/scalelite.yml
      group: root
      mode: 0644
      owner: root
      src: scalelite.j2
  - block:
    - name: Installs BigBlueButton SSH Configuration Directory
      file:
        dest: /home/bigbluebutton/.ssh
        group: bigbluebutton
        mode: 0700
        owner: bigbluebutton
        state: directory
    - name: Installs BigBlueButton SSH Configuration
      template:
        dest: /home/bigbluebutton/.ssh/config
        group: bigbluebutton
        mode: 0600
        owner: bigbluebutton
        src: ssh-config.j2
    when:
    - hostvars[groups['scalelite'][0]]['corosync_vip'] is defined
  - name: Installs BigBlueButton/Scalelite Recordings Post Process Script
    get_url:
      dest: /usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb
      group: root
      mode: 0755
      owner: root
      url: https://raw.githubusercontent.com/blindsidenetworks/scalelite/master/bigbluebutton/scalelite_post_publish.rb
    register: has_postpublish
  - name: Installs BigBlueButton/Scalelite Recordings Migration Script
    get_url:
      dest: /root/scalelite_batch_import.sh
      group: root
      mode: 0755
      owner: root
      url: https://raw.githubusercontent.com/blindsidenetworks/scalelite/master/bigbluebutton/scalelite_batch_import.sh
  - include_role:
      name: sshfs
      tasks_from: user.yaml
    vars:
      ssh_user: bigbluebutton
  when:
  - groups['scalelite'] | length > 0

- block:
  - block:
    - name: Clones BigBlueButton/MP4 Recordings Post Process Assets
      git:
        dest: /usr/src/bbb-download
        repo: 'https://github.com/createwebinar/bbb-download'
        update: no
      register: bbbmp4
    - name: Installs BigBlueButton/MP4 Recordings Post Process Assets
      args:
        chdir: /usr/src/bbb-download
        creates: /var/bigbluebutton/published/presentation
      shell: sh install.sh
    when:
    - bigbluebutton_version in [ 22, '22' ]
  - block:
    - name: Clones BigBlueButton/MP4 Recordings Post Process Assets
      git:
        dest: /var/www/bbb-mp4
        repo: 'https://github.com/manishkatyan/bbb-mp4'
        update: no
      register: bbbmp4
    - name: Creates BigBlueButton/MP4 Working Directories
      file:
        dest: "{{ fl }}"
        group: root
        mode: 0755
        owner: root
        state: directory
      loop:
      - /var/www
      - /var/www/bigbluebutton-default
      - /var/www/bigbluebutton-default/recording
      - /var/www/bbb-mp4/webm
      - /var/www/bbb-mp4/download
      loop_control:
        loop_var: fl
    - name: Installs BigBlueButton/MP4 environment configuration
      template:
        dest: /var/www/bbb-mp4/.env
        group: root
        mode: 0644
        owner: root
        src: bbb-mp4.j2
    - name: Installs BigBlueButton/MP4 Recordings Post Process Assets
      args:
        chdir: /var/www/bbb-mp4
      environment:
        PATH: /usr/sbin:/usr/bin:/sbin:/bin:/var/www/bbb-mp4
      shell: ./bbb-mp4-install.sh
    when:
    - not (bigbluebutton_version in [ 22, '22' ])
  when:
  - do_bbb_mp4_convert | default(False)

- name: Sets HSTS Header
  lineinfile:
    dest: /etc/nginx/sites-available/bigbluebutton
    line: '    add_header Strict-Transport-Security "max-age=31536001; includeSubDomains" always;'
    regex: "add_header Strict-Transport-Security"
  notify: Reloads Nginx

- name: Configures BigBlueButton TURN Integration
  register: turn_conf
  template:
    dest: /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
    group: bigbluebutton
    mode: 0640
    owner: root
    src: turn.j2

- name: Fixes Meteor TLS Errors
  register: meteor_fixed
  lineinfile:
    dest: /usr/share/meteor/bundle/systemd_start.sh
    insertbefore: "^PORT=3000"
    line: "export NODE_TLS_REJECT_UNAUTHORIZED=0"
    regexp: "^export NODE_TLS_REJECT_UNAUTHORIZED=0"
  when:
  - bbb_uses_selfsigned | default(True)

- block:
  - name: Installs FreeSwitch SIP Trunk Configuration
    register: fcf1
    template:
      dest: "/opt/freeswitch/conf/sip_profiles/external/{{ freeswitch_trunk_name }}.xml"
      group: daemon
      mode: 0640
      owner: freeswitch
      src: fs-external.j2
  - name: Installs FreeSwitch SIP DIDs Configuration
    register: fcf2
    template:
      dest: "/opt/freeswitch/conf/dialplan/public/{{ freeswitch_trunk_name }}.xml"
      group: daemon
      mode: 0640
      owner: freeswitch
      src: fs-route.j2
  - name: Restarts FreeSwitch
    service:
      name: freeswitch
      state: restarted
    when:
    - >
        (fcf1 is defined
         and fcf1 is changed)
        or (fcf2 is defined
         and fcf2 is changed)
  - name: Sets BBB Phone Number
    lineinfile:
      dest: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
      line: "defaultDialAccessNumber={{ freeswitch_trunk_dids[0] }}"
      regex: ^defaultDialAccessNumber=
    register: fixed_did
  - name: Sets BBB Welcome Footer
    lineinfile:
      dest: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
      line: "defaultWelcomeMessageFooter=<br><br>To join this meeting by phone, dial:<br>  %%DIALNUM%%<br>Then enter %%CONFNUM%% as the conference PIN number."
      regex: ^defaultWelcomeMessageFooter=
    register: fixed_footer
  when:
  - freeswitch_trunk_dids is defined
  - freeswitch_trunk_dids | length > 0
  - freeswitch_trunk_password is defined
  - freeswitch_trunk_username is defined

- name: Restarts BigBlueButton
  shell: bbb-conf --restart
  when:
  - >
      (fixed_home is defined
       and fixed_home is changed)
      or (fixed_did is defined
       and fixed_did is changed)
      or (fixed_footer is defined
       and fixed_footer is changed)
      or (fixed_meteor is defined
       and fixed_meteor is changed)
      or (has_demo is defined
       and has_demo is changed)
      or (has_postpublish is defined
       and has_postpublish is changed)
      or (turn_conf is defined
       and turn_conf is changed)
