- name: Gather Facts from Scalelite
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['scalelite'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['scalelite'] | length > 0
- name: Gather Facts from Coturn
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['coturn'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['coturn'] | length > 0
