- name: Gather Facts from Scalelite
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['scalelite'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['scalelite'] | length > 0
- name: Gather Facts from Coturn
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['coturn'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['coturn'] | length > 0
- block:
  - name: Sets BigBlueButton Version According to OS
    set_fact:
      bigbluebutton_version: "{{ 23 if (ansible_distribution_release == 'bionic')
                                    else (22 if (ansible_distribution_release == 'xenial')
                                             else 0) }}"
  - name: Fails if Discovered Version is Invalid
    fail:
      msg: |
        Could not set BigBlueButton version
        BigBlueButton should be deployed on Ubuntu, either xenial (2.2) or bionic (2.3)
    when:
    - bigbluebutton_version not in [ 22, '22', 23, '23' ]
  when:
  - not (bigbluebutton_version | default(False))
