- name: Clones Kurento Monitor
  git:
    dest: /usr/src/kurento-monitor
    repo: 'https://github.com/Worteks/kurento-monitor'
    update: no
    version: wip-prometheus
- name: Installs Dependencies
  args:
    chdir: /usr/src/kurento-monitor
    creates: /usr/src/kurento-monitor/node_modules
  command: npm install
- name: Downgrades modules syntax for NodeJS 8
  args:
    chdir: /usr/src/kurento-monitor
    creates: /usr/src/kurento-monitor/.patched
    executable: /bin/bash
  shell: |
    set -o pipefail && \
    find node_modules/prom-client/ -type f | while read line;
        do sed -i "s|} catch {|} catch(nvm) {|" "$line";
        done && date >.patched
- name: Installs Kurento Exporter Configuration
  template:
    dest: /usr/src/kurento-monitor/config/default.json
    group: root
    mode: 0644
    owner: root
    src: kr-config.j2
- name: Creates Kurento Exporter Group
  group:
    name: kurentoexporter
    state: present
- name: Creates Kurento Exporter User
  user:
    groups: kurentoexporter
    name: kurentoexporter
- name: Installs Kurento Exporter Unit
  register: exporter_unit
  template:
    dest: /etc/systemd/system/kurento-exporter.service
    group: root
    mode: 0644
    owner: root
    src: kr-exporter.j2
- name: Reloads Systemd Configuration
  systemd:
    daemon_reload: yes
  when:
  - exporter_unit is defined
  - exporter_unit is changed
- name: Ensures Kurento Exporter is Running & Starts on Boot
  service:
    enabled: yes
    name: kurento-exporter
    state: started
