# !! WARNING !!
# Would not work with bbb-2.2
# relies on some async library that is missing with Python 3.5.2 (which is
#  the maximum we can get ... I'ld rather not try further. I'll go back to
#  my initial idea: using a container. And enable host networking, to
#  avoid reconfiguring freeswitch admin bind address.
# also: Python 3.6 probably preferred - before finding about that issue,
#  I patched a bunch of syntax errors, ... that were not an issue, running
#  on top of python:3-slim-buster. Xenial is the main issue here....

- name: Installs Python Virtualenv
  apt:
    name:
    - python-pip-whl
    - python3-venv
    - virtualenv
    state: present
- name: Installs FreeSwitch Exporter Virtualenv Directory Root
  file:
    dest: /var/lib/freeswitch-exporter
    group: root
    mode: 0755
    owner: root
    state: directory
- name: Initializes FreeSwitch Exporter Virtualenv Directory
  args:
    creates: /var/lib/freeswitch-exporter/pyenv.cfg
  shell: python3 -m venv /var/lib/freeswitch-exporter
- name: Installs FreeSwitch Exporter Dependencies in FreeSwitch Exporter Virtualenv
  pip:
    name:
    - setuptools
    - wheel
    virtualenv: /var/lib/freeswitch-exporter
- name: Installs FreeSwitch Exporter in FreeSwitch Exporter Virtualenv
  pip:
    name: prometheus-freeswitch-exporter
    virtualenv: /var/lib/freeswitch-exporter

- name: Fetches Freeswitch Event Socket Password
  args:
    chdir: /opt/freeswitch/etc/freeswitch/autoload_configs
  changed_when: False
  register: fs_secret
  shell: "awk '/password/{print $3}' event_socket.conf.xml | sed -e 's|.*value=.||' -e 's|./>$||'"
- name: Installs FreeSwitch Exporter Configuration
  template:
    dest: /var/lib/freeswitch-exporter/esl.yaml
    group: root
    mode: 0640
    owner: root
    src: esl.j2

- name: Installs Freeswitch Exporter Service Configuration
  register: exporter_unit
  template:
    dest: /etc/systemd/system/freeswitch-exporter.service
    group: root
    mode: 0644
    owner: root
    src: fs-exporter.j2
- name: Reloads Systemd Configuration
  shell: systemctl daemon-reload
  when:
  - exporter_unit is defined
  - exporter_unit is changed
- name: Ensures Freeswitch Exporter is Running & Starts on Boot
  service:
    enabled: yes
    name: freeswitch-exporter
    state: started
