- include_tasks: prom-bbb.yaml
- include_tasks: prom-freeswitch.yaml
- include_role:
    name: nginx
    tasks_from: prometheus.yaml
- include_role:
    name: redis
    tasks_from: prometheus.yaml
- include_role:
    name: mongodb
    tasks_from: prometheus.yaml
  vars:
    mongodb_listen_address: 127.0.1.1
# TODO: completion ..
