blackbox_exporter_port: 9158
blackbox_exporter_release: 0.17.0
blackbox_exporter_repo: https://github.com/prometheus/blackbox_exporter

nginx_ssl_ciphers:
- EECDH+ECDSA+AESGCM
- EECDH+aRSA+AESGCM
- EECDH+ECDSA+SHA512
- EECDH+ECDSA+SHA384
- EECDH+ECDSA+SHA256
- '!aNULL'
- '!eNULL'
- '!LOW'
- '!RC4'
- '!3DES'
- '!MD5'
- '!EXP'
- '!PSK'
- '!SRP'
- '!DSS'
nginx_ssl_protocols:
- TLSv1.2

greenlight_help_url: https://docs.bigbluebutton.org/greenlight/gl-overview.html
greenlight_images_release: release-2.9.1
greenlight_images_repo: docker.io/bigbluebutton/greenlight

greenlight_allow_local_accounts: True

greenlight_admin_account: gladmin
greenlight_admin_email: gladmin@demo.local
greenlight_admin_password: secret

greenlight_ldap_auth: user
greenlight_ldap_base: dc=demo,dc=local
greenlight_ldap_bind_dn: cn=admin,dc=demo,dc=local
#greenlight_ldap_endpoint: ldap://directory.example.com:1636
greenlight_ldap_password: changeme
greenlight_ldap_role_field: userRole
greenlight_ldap_user_objectclass: inetOrgPerson
greenlight_ldap_uid: uid

greenlight_oidc_authorization_endpoint: /oauth2/authorize
greenlight_oidc_client_id: greenlight
greenlight_oidc_client_secret: changeme
#greenlight_oidc_endpoint: "{{ greenlight_oidc_site }}{{ greenlight_oidc_authorization_endpoint }}"
#greenlight_oidc_site: https://auth.example.com
greenlight_oidc_token_endpoint: /oauth2/token
#greenlight_oidc_logout_endpoint: /oauth2/slo
greenlight_oidc_uid_field: sub

greenlight_postgres_database: greenlight
#greenlight_postgres_host: False -- detected from inventory
greenlight_postgres_password: greenlightpw
greenlight_postgres_port: 5432
greenlight_postgres_user: greenlightusr

#SHA1 fingerprint for SAML provider, generate with:
greenlight_saml_cert_fingerprint: CH:AN:GE:ME:...
greenlight_saml_commonname_field: uid
greenlight_saml_email_field: mail
#greenlight_saml_endpoint: https://auth.example.com/saml/singleSignOn
greenlight_saml_nameid_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
greenlight_saml_issuer: greenlight
greenlight_saml_uid_field: uid
greenlight_saml_username_field: uid

greenlight_smtp_auth: plain
#greenlight_smtp_domain: "{{ ansible_fqdn }}"
greenlight_smtp_password: False
greenlight_smtp_port: 25
greenlight_smtp_server: False
greenlight_smtp_starttls: False
greenlight_smtp_testuser: False
greenlight_smtp_tls: False
greenlight_smtp_username: False

greenlight_app_root: /b
greenlight_registrations: invite
greenlight_room_features:
- mute-on-join
- require-moderator-approval
- anyone-can-start
- all-join-moderator
- recording

greenlight_base_secret: changemechangemechangemechangemechangemechangemechangemechangemechangemechangemechangemechangemechangemechangemechangemechangemec
