- name: Gather Facts from Postgres
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['postgres_peertube'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
- name: Gather Facts from Redis
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['redis_peertube'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
- name: Gather Facts from Redis LoadBalancers
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['lb_back'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['lb_back'] | length > 0
- name: Gather Facts from PeerTube Nodes
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['peertube'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
# ^ only required when applying playbook to a single PT node,
#   while the peertube group has several hosts: we would add
#   all their IPs to the trust_proxy configuration, ...
