- name: "Creates PeerTube SSH Key Pair on {{ srv }}"
  args:
    chdir: /root/.ssh
    creates: /root/.ssh/id_rsa
  delegate_to: "{{ srv }}"
  run_once: yes
  shell: |
    /usr/bin/ssh-keygen -t rsa -b 4096 -N '' -f id_rsa
- name: "Fetches PeerTube Public SSH Key from {{ srv }}"
  args:
    chdir: /root/.ssh
  changed_when: False
  delegate_to: "{{ srv }}"
  register: has_key
  run_once: yes
  shell: cat id_rsa.pub
- name: "Ensures {{ srv }} Key is Trusted"
  lineinfile:
    create: yes
    dest: "/root/.ssh/{{ keyfile }}"
    group: root
    line: "{{ has_key.stdout_lines[0] }}"
    mode: 0600
    owner: root
  loop:
  - authorized_keys
  - instance_keys
  loop_control:
    loop_var: keyfile
