- name: Installs PeerTube Docker-Compose Directory
  file:
    dest: /etc/docker-compose/peertube
    group: root
    mode: 0755
    owner: root
    state: directory
- block:
  - name: Installs PeerTube Patch Root Directory
    file:
      dest: /usr/src/docker-peertube
      group: root
      mode: 0755
      owner: root
      state: directory
  - name: Installs PeerTube Patch Dockerfile
    register: ptdkr
    template:
      dest: /usr/src/docker-peertube/Dockerfile
      group: root
      mode: 0644
      owner: root
      src: Dockerfile.j2
  - name: Builds PeerTube Patched Image
    args:
      chdir: /usr/src/docker-peertube
    shell: |
      docker build -t peertube-patched:{{ peertube_images_release }} . >custom-image-build.$(date +%s).log 2>&1
    when:
    - ptdkr is defined
    - ptdkr is changed
  when:
  - peertube_multipart_patch | default(False)
- include_role:
    name: docker
    tasks_from: check-pull.yaml
  vars:
    image_tag: "{{ peertube_images_release }}"
    image_url: "{{ peertube_images_repo }}"
  when:
  - not (peertube_multipart_patch | default(False))
