- include_role:
    name: docker
    tasks_from: check-pull.yaml
  vars:
    image_tag: "{{ peertubeexporter_images_release }}"
    image_url: "{{ peertubeexporter_images_repo }}"
- name: Installs PeerTube Exporter Docker-Compose Directory
  file:
    dest: /etc/docker-compose/peertube-exporter
    group: root
    mode: 0755
    owner: root
    state: directory
- name: Installs PeerTube Exporter Configuration
  register: should_reload
  template:
    dest: /etc/docker-compose/peertube-exporter/docker-compose.yaml
    group: root
    mode: 0640
    owner: root
    src: exporter.j2
- include_role:
    name: docker
    tasks_from: service.yaml
  vars:
    service_description: PeerTube Exporter
    service_name: peertube-exporter
    service_standby: "{{ False if ((groups['peertube'] | first) == ansible_nodename)
                               else True }}"
- block:
  - include_role:
      name: pacemaker
      tasks_from: add-service.yaml
    vars:
      service_id: Nginxxp-rsc
      service_name: nginx-exporter
      service_timeout: 200
      service_type: systemd
  - include_role:
      name: pacemaker
      tasks_from: add-service.yaml
    vars:
      service_id: Peertubexp-rsc
      service_name: peertube-exporter
      service_timeout: 300
      service_type: systemd
  - include_role:
      name: pacemaker
      tasks_from: finish-setup.yaml
    vars:
      drbd_facts_reset: False
  when:
  - >
      ansible_fqdn in groups['drbd']
      or ansible_hostname in groups['drbd']
      or ansible_nodename in groups['drbd']
  - corosync_hostgroup | default(False)
