- name: Installs Peertube Videos Sync Script
  template:
    dest: /usr/local/bin/peertube-sync-videos
    group: root
    mode: 0755
    owner: root
    src: sync-videos.j2
- include_tasks: import-pt-key.yaml
  loop: "{{ groups['peertube'] }}"
  loop_control:
    loop_var: srv
  when:
  - srv not in [ ansible_hostname, ansible_fqdn, ansible_nodename ]
# FIXME: trust remote hostkeys
# doesn't seem to be needed ATM, might be thanks to freeipa?
- block:
  - name: Installs PeerTube Videos Sync Job
    copy:
      dest: "/etc/systemd/system/peertube-backup.{{ item }}"
      group: root
      mode: 0644
      owner: root
      src: "backup-{{ item }}"
    loop:
    - service
    - timer
    register: bkpunit
  - name: Reloads Systemd Configuration
    systemd:
      daemon_reload: yes
    when:
    - bkpunit is defined
    - bkpunit is changed
  - name: Enables PeerTube Videos Sync Job
    service:
      enabled: yes
      name: peertube-backup.timer
      state: started
  when:
  - groups['peertube'][0] in [ ansible_hostname, ansible_fqdn, ansible_nodename ]
