- name: Reloads Nginx
  service:
    name: nginx
    state: restarted
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']
- name: Reloads Nginx Exporter
  service:
    name: nginx-exporter
    state: restarted
  when:
  - >
       (nginx_drbd_should_run
        and (ansible_fqdn in groups['drbd']
             or ansible_nodename in groups['drbd']
             or ansible_hostname in groups['drbd']))
       or (ansible_fqdn not in groups['drbd']
          and ansible_nodename not in groups['drbd']
          and ansible_hostname not in groups['drbd'])
