- name: Fetches BigBlueButton API Secret
  args:
    executable: /bin/bash
  changed_when: False
  delegate_to: "{{ stream_hosted_on | default(groups['bbb'][0]) }}"
  register: bbb_secret
  run_once: yes
  shell: |
    set -o pipefail && \
    bbb-conf --secret | awk '/Secret:/{print $2}'
  when:
  - >
      (groups['scalelite'] | length == 0)
      or stream_hosted_on | default(False)
- name: "Resolves Meeting ID for {{ stream_meeting_id }}"
  args:
    executable: /bin/bash
  changed_when: False
  delegate_to: "{{ stream_hosted_on | default(groups['bbb'][0]) }}"
  register: bbb_meeting
  run_once: yes
  shell: |
    set -o pipefail && \
    bbb-cli get-rooms \
        | grep -A1 "<meetingName>{{ stream_meeting_id }}</meetingName>" \
        | grep '<meetingID>' \
        | sed -e 's|.*<meetingID>||' -e 's|</meetingID>.*||'
- name: "Installs BigBlueButton LiveStream {{ stream_meeting_id }} Docker Configuration Directory"
  file:
    dest: "/etc/docker-compose/bbb-livestream-{{ stream_meeting_id }}"
    group: root
    mode: 0755
    owner: root
    state: directory
- name: "Installs BigBlueButton LiveStream {{ stream_meeting_id }} Configuration"
  register: should_reload
  template:
    dest: "/etc/docker-compose/bbb-livestream-{{ stream_meeting_id }}/docker-compose.yaml"
    group: root
    mode: 0640
    owner: root
    src: compose.j2
- include_role:
    name: docker
    tasks_from: service.yaml
  vars:
    service_description: "BigBlueButton LiveStream {{ stream_meeting_id }}"
    service_name: "bbb-livestream-{{ stream_meeting_id }}"
