- name: Reloads Postgres
  service:
    name: postgresql
    state: restarted
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_hostname not in groups['drbd']
  - ansible_nodename not in groups['drbd']
- name: Reloads Postgres Exporter
  service:
    name: "postgres-exporter-{{ scalelite_postgres_database
                                   if (ansible_fqdn in groups['postgres_scalelite']
                                       or ansible_hostname in groups['postgres_scalelite']
                                       or ansible_nodename in groups['postgres_scalelite'])
                                   else (coturn_postgres_database
                                         if (ansible_fqdn in groups['postgres_coturn']
                                             or ansible_hostname in groups['postgres_coturn']
                                             or ansible_nodename in groups['postgres_coturn'])
                                         else (moodle_postgres_database
                                               if (ansible_fqdn in groups['postgres_moodle']
                                                   or ansible_hostname in groups['postgres_moodle']
                                                   or ansible_nodename in groups['postgres_moodle'])
                                               else (openstreamingplatform_postgres_database
                                                     if (ansible_fqdn in groups['postgres_openstreamingplatform']
                                                         or ansible_hostname in groups['postgres_openstreamingplatform']
                                                         or ansible_nodename in groups['postgres_openstreamingplatform'])
                                                     else (peertube_postgres_database
                                                           if (ansible_fqdn in groups['postgres_peertube']
                                                               or ansible_hostname in groups['postgres_peertube']
                                                               or ansible_nodename in groups['postgres_peertube'])
                                                           else (grafana_postgres_database
                                                                 if (ansible_fqdn in groups['postgres_grafana']
                                                                     or ansible_hostname in groups['postgres_grafana']
                                                                     or ansible_nodename in groups['postgres_grafana'])
                                                                 else (greenlight_postgres_database
                                                                       if (ansible_fqdn in groups['postgres_greenlight']
                                                                           or ansible_hostname in groups['postgres_greenlight']
                                                                           or ansible_nodename in groups['postgres_greenlight'])
                                                                       else 'postgres')))))) }}"
    state: restarted
  when:
  - >
       (postgres_exporter_should_run | default(False)
        and (ansible_fqdn in groups['drbd']
             or ansible_nodename in groups['drbd']
             or ansible_hostname in groups['drbd']))
       or (ansible_fqdn not in groups['drbd']
          and ansible_nodename not in groups['drbd']
          and ansible_hostname not in groups['drbd'])
