kibana_es_request_timeout: 30

#kibana_fqdn: kibana.example.com        defaults to fqdn

kibana_images_release: 7.12.1
kibana_images_repo: docker.elastic.co/kibana/kibana

kibana_prometheus_plugin: "https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/{{ kibana_images_release }}/kibanaPrometheusExporter-{{ kibana_images_release }}.zip"
