- name: "Checks DRBD:{{ drbd_id | default('r0') }} configured"
  changed_when: False
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  failed_when: False
  register: hasdrbd
  run_once: yes
  shell: |
    crm configure show | grep "primitive DRBD_{{ drbd_id | default('r0') }} "
- block:
  - name: "Configures DRBD:{{ drbd_id | default('r0') }} primitive"
    delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
    run_once: yes
    shell: |
      crm configure primitive DRBD_{{ drbd_id | default('r0') }} \
          ocf:linbit:drbd drbd_resource="{{ drbd_name | default(drbd_resource_name) }}" \
          op start interval="0" timeout="240" \
          op stop interval="0" timeout="100" \
          op monitor role=Master interval=59s timeout=30s \
          op monitor role=Slave interval=60s timeout=30s
  - name: Gives it a few seconds
    delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
    pause:
      seconds: 5
    run_once: yes
  when:
  - hasdrbd is defined
  - hasdrbd.rc is defined
  - (hasdrbd.rc | default(0)) != 0
- include_tasks: add-master.yaml
