- name: "Checks VIP:{{ vip }} configured"
  changed_when: False
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  failed_when: False
  register: hasvip
  run_once: yes
  shell: |
    crm configure show | grep -A1 'primitive IP-' | grep -E ' ip={{ vip }}($| )'
- name: "Configures VIP:{{ vip }} primitive"
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  run_once: yes
  shell: |
    crm configure primitive IP-rsc \
        ocf:heartbeat:IPaddr2 ip={{ vip }} \
        nic={{ vip_iface | default(ansible_default_ipv4['interface']) }} \
        cidr_netmask={{ vip_netmask | default(24) }} \
        meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
  when:
  - hasvip is defined
  - hasvip.rc is defined
  - (hasvip.rc | default(0)) != 0
