- name: Checks Resource Group Configured
  args:
    executable: /bin/bash
  changed_when: False
  delegate_to: "{{ groups[corosync_hostgroup | default('pacemaker')][0] }}"
  failed_when: False
  register: hasgroup
  run_once: yes
  shell: |
    set -o pipefail && \
    crm configure show | grep '^group APCLUSTER '
- block:
  - name: Lists LVM primitives
    changed_when: False
    delegate_to: "{{ groups[corosync_hostgroup | default('pacemaker')][0] }}"
    failed_when: False
    register: haslvms
    run_once: yes
    shell: |
      crm configure show | awk '/^primitive/{print $2}' | grep ^LVM
  - name: Lists Mount primitives
    changed_when: False
    delegate_to: "{{ groups[corosync_hostgroup | default('pacemaker')][0] }}"
    failed_when: False
    register: hasmounts
    run_once: yes
    shell: |
      crm configure show | awk '/^primitive/{print $2}' | grep ^SRV_MOUNT
  - name: Lists IP primitives
    changed_when: False
    delegate_to: "{{ groups[corosync_hostgroup | default('pacemaker')][0] }}"
    failed_when: False
    register: hasips
    run_once: yes
    shell: |
      crm configure show | awk '/^primitive/{print $2}' | grep ^IP
  - name: Lists Services primitives
    changed_when: False
    delegate_to: "{{ groups[corosync_hostgroup | default('pacemaker')][0] }}"
    failed_when: False
    register: hassvcs
    run_once: yes
    shell: |
      crm configure show | awk '/^primitive/{print $2}' | grep -v ^IP | grep -E '.*-rsc'
  - name: Sets Resource Group Facts
    run_once: yes
    set_fact:
      group_deps: "{{ ((haslvms.stdout_lines | default([]))
                       + (hasmounts.stdout_lines | default([]))
                       + (hasips.stdout_lines | default([]))
                       + (hassvcs.stdout_lines | default([]))) | join(' ') }}"
  - name: Creates Resource Group
    any_errors_fatal: true
    command: |
      crm configure group APCLUSTER {{ group_deps }}
    delegate_to: "{{ groups[corosync_hostgroup | default('pacemaker')][0] }}"
    run_once: yes
  when:
  - hasgroup is defined
  - hasgroup.rc is defined
  - (hasgroup.rc | default(0)) != 0
