- name: "Checks LVM:{{ vg_id | default('r0') }} configured"
  changed_when: False
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  failed_when: False
  register: haslvm
  run_once: yes
  shell: |
    crm configure show | grep "primitive LVM_{{ vg_id | default('r0') }} "
- name: "Configures LVM:{{ vg_id | default('r0') }} primitive"
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  run_once: yes
  shell: |
    crm configure primitive LVM_{{ vg_id | default('r0') }} \
        ocf:heartbeat:LVM \
        volgrpname="{{ vg_name | default('data') }}" \
        op monitor interval="30s"
  when:
  - haslvm is defined
  - haslvm.rc is defined
  - (haslvm.rc | default(0)) != 0
