- name: Checks Master/Slave Configured
  args:
    executable: /bin/bash
  changed_when: False
  delegate_to: "{{ groups[corosync_hostgroup | default('pacemaker')][0] }}"
  failed_when: False
  register: hasms
  run_once: yes
  shell: |
    set -o pipefail && \
    crm configure show | grep '^ms {{ drbd_ms_name | default("ms_DRBD_" ~ (drbd_id | default("r0"))) }} '
- name: Creates Master/Slave Primitive
  any_errors_fatal: true
  command: |
    crm configure ms {{ drbd_ms_name | default("ms_DRBD_" ~ (drbd_id | default("r0"))) }} \
        DRBD_{{ drbd_id | default("r0") }} \
        meta master-max="1" master-node-max="1" clone-max="2" clone-node-max="1" notify="true"
  delegate_to: "{{ groups[corosync_hostgroup | default('pacemaker')][0] }}"
  run_once: yes
  when:
  - hasms is defined
  - hasms.rc is defined
  - (hasms.rc | default(0)) != 0
