- name: Checks Colocation Configured
  changed_when: False
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  failed_when: False
  register: hascoloc
  run_once: yes
  shell: |
    crm configure show | grep '^colocation APCLUSTER_on_DRBD_{{ drbd_id | default("r0") }}'
- name: Configures Colocation
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  run_once: yes
  shell: |
    crm configure colocation APCLUSTER_on_DRBD_{{ drbd_id | default("r0") }} \
        'inf:' APCLUSTER '{{ drbd_ms_name | default("ms_DRBD_" ~ (drbd_id | default("r0"))) }}:Master'
  when:
  - hascoloc is defined
  - hascoloc.rc is defined
  - (hascoloc.rc | default(0)) != 0
- name: Checks Order Configured
  changed_when: False
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  failed_when: False
  register: hasorder
  run_once: yes
  shell: |
    crm configure show | grep '^order APCLUSTER_after_DRBD_{{ drbd_id | default("r0") }}'
- name: Configures Order
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  run_once: yes
  shell: |
    echo y | crm configure order APCLUSTER_after_DRBD_{{ drbd_id | default("r0") }} \
        'Mandatory:' '{{ drbd_ms_name | default("ms_DRBD_" ~ (drbd_id | default("r0"))) }}:promote' 'APCLUSTER:start'
  when:
  - hasorder is defined
  - hasorder.rc is defined
  - (hasorder.rc | default(0)) != 0
- name: Cleanup Pacemaker Alerts
  changed_when: False
  delay: 300
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  register: reloadrslt
  retries: 3
  run_once: yes
  shell: |
    pcs resource cleanup
  until: reloadrslt.rc == 0
