- name: "Checks SERVICE:{{ service_id | default(1) }} configured"
  args:
    executable: /bin/bash
  changed_when: False
  delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
  failed_when: False
  register: hassvc
  run_once: yes
  shell: |
    set -o pipefail && \
    crm configure show | grep "primitive {{ service_id }} {{ service_type | default('lsb') }}:"
- block:
  - name: "Configures SERVICE:{{ lvm_id | default(1) }} primitive"
    command: |
      crm configure primitive {{ service_id }} \
          {{ service_type }}:{{ service_name }} \
          meta migration-threshold=2 op monitor interval=20 timeout={{ service_timeout | default(60) }} on-fail=restart
    delegate_to: "{{ groups[corosync_hostgroup | default('corosync')][0] }}"
    run_once: yes
  when:
  - hassvc is defined
  - hassvc.rc is defined
  - (hassvc.rc | default(0)) != 0
