- name: Installs pexpect
  apt:
    name: python-pexpect
    state: present

## TODO/FIXME fucked-up ...
## peertube-db sample, in `crm configure`, type:

# primitive DRBD_r0 ocf:linbit:drbd params drbd_resource="r0" op start interval="0" timeout="240" op stop interval="0" timeout="100" op monitor role=Master interval=59s timeout=30s op monitor role=Slave interval=60s timeout=30s
# primitive LVM_r0 ocf:heartbeat:LVM params volgrpname="data" op monitor interval="30s"
# primitive SRV_MOUNT_1 ocf:heartbeat:Filesystem params device="/dev/mapper/data-postgres" directory="/var/lib/postgresql" fstype="xfs" options="noatime,nodiratime,noexec,nodev,nosuid" op monitor interval="40s"
# primitive SRV_MOUNT_2 ocf:heartbeat:Filesystem params device="/dev/mapper/data-redis" directory="/var/lib/redis" fstype="xfs" options="noatime,nodiratime,noexec,nodev,nosuid" op monitor interval="40s"
# primitive IP-rsc ocf:heartbeat:IPaddr2 params ip="192.168.255.52" nic="priv0" cidr_netmask="24" meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
# primitive Postgresql-rsc lsb:postgresql meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
#NOPE primitive Postgresxp-rsc lsb:postgres-exporter-peertube meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
# primitive Redis-rsc lsb:redis-server meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
#NOPE primitive Redisxp-rsc lsb:redis-exporter meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
#NOPE primitive Peertube-rsc lsb:peertube meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
#NOPE primitive Peertubexp-rsc lsb:peertube-exporter meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
# primitive Nginx-rsc lsb:nginx meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
#NOPE primitive Nginxxp-rsc lsb:nginx-exporter meta migration-threshold=2 op monitor interval=20 timeout=60 on-fail=restart
# group APCLUSTER LVM_r0 SRV_MOUNT_1 IP-rsc Postgresql-rsc Postgresxp-rsc Redis-rsc Redisxp-rsc Peertube-rsc Peertubexp-rsc Nginx-rsc
# ms ms_DRBD_APCLUSTER DRBD_r0 meta master-max="1" master-node-max="1" clone-max="2" clone-node-max="1" notify="true"
# colocation APCLUSTER_on_DRBD_r0 inf: APCLUSTER ms_DRBD_APCLUSTER:Master
# order APCLUSTER_after_DRBD_r0 inf: ms_DRBD_APCLUSTER:promote APCLUSTER:start
# commit

##//
