alertmanager_images_release: v0.23.0
alertmanager_images_repo: docker.io/prom/alertmanager

alertmanager_notify_slack_send_resolved: True
alertmanager_notify_slack_address: False
alertmanager_notify_smtp_send_resolved: True
alertmanager_notify_smtp_address: root@demo.local

alertmanager_repeat_interval_default: 12h
alertmanager_repeat_interval_critical: 3h
alertmanager_repeat_interval_warning: 6h

#alertmanager_smtp_domain: "{{ ansible_fqdn }}"
alertmanager_smtp_password: False
alertmanager_smtp_port: 25
alertmanager_smtp_server: False
alertmanager_smtp_tls: False
alertmanager_smtp_username: False

nginx_ssl_ciphers:
- EECDH+ECDSA+AESGCM
- EECDH+aRSA+AESGCM
- EECDH+ECDSA+SHA512
- EECDH+ECDSA+SHA384
- EECDH+ECDSA+SHA256
- '!aNULL'
- '!eNULL'
- '!LOW'
- '!RC4'
- '!3DES'
- '!MD5'
- '!EXP'
- '!PSK'
- '!SRP'
- '!DSS'
nginx_ssl_protocols:
- TLSv1.2
