- name: "Installs {{ site_fqdn }} Htpasswd Configuration"
  template:
    dest: "/etc/nginx/htpasswd.{{ site_fqdn }}.conf"
    group: www-data
    mode: 0640
    owner: root
    src: htpasswd.j2
  when:
  - reverse_htpasswd is defined
  - reverse_htpasswd[site_fqdn] is defined
- name: "Installs {{ site_fqdn }} Virtualhost"
  notify: Reloads Nginx
  template:
    dest: /etc/nginx/sites-available/{{ site_fqdn }}.conf
    group: root
    mode: 0644
    owner: root
    src: "{{ tplate }}.j2"
- name: "Enables {{ site_fqdn }} Virtualhost"
  file:
    dest: /etc/nginx/sites-enabled/{{ site_fqdn }}.conf
    src: /etc/nginx/sites-available/{{ site_fqdn }}.conf
    state: link
  notify: Reloads Nginx
