- name: Creates ElasticSearch Group
  group:
    name: elasticsearch
    state: present
- name: Creates ElasticSearch User
  user:
    groups: elasticsearch
    name: elasticsearch
- name: Resolves ElasticSearch User ID
  args:
    executable: /bin/bash
  changed_when: False
  register: elasticsearch_user_id
  shell: |
    set -o pipefail && \
    getent passwd elasticsearch | awk -F: '{print $3;exit;}'
- name: Installs ElasticSearch Database Directory
  file:
    dest: /var/lib/elasticsearch
    group: elasticsearch
    mode: 0755
    owner: elasticsearch
    state: directory
- include_role:
    name: docker
    tasks_from: check-pull.yaml
  vars:
    image_tag: "{{ opensearch_images_release
                     if (storage_flavor == 'open')
                     else elasticsearch_images_release }}"
    image_url: "{{ opensearch_images_repo
                     if (storage_flavor == 'open')
                     else elasticsearch_images_repo }}"
