- name: "Installs {{ service_description | default(service_name) }} Unit"
  register: docker_unit
  template:
    dest: "/etc/systemd/system/{{ service_name }}.service"
    group: root
    mode: 0644
    owner: root
    src: compose-systemd.j2
- name: Reloads Systemd Configuration
  shell: systemctl daemon-reload
  when:
  - docker_unit is defined
  - docker_unit is changed
- block:
  - name: "Ensures {{ service_description | default(service_name) }} is Running & Starts on Boot"
    register: did_start
    service:
      enabled: "{{ 'no' if (service_standby | default(False))
                        else 'yes' }}"
      name: "{{ service_name }}"
      state: "{{ 'stopped' if (service_standby | default(False))
                           else 'started' }}"
  - name: "Restarts {{ service_description | default(service_name) }}"
    service:
      name: "{{ service_name }}"
      state: restarted
    when:
    - did_start is defined
    - not (service_standby | default(False))
    - not (did_start is changed)
    - >
        (should_reload is defined
         and should_reload is changed)
        or (config_changed is defined
         and config_changed is changed)
  when:
  - >
      (service_force_drbd | default(False))
      or (ansible_fqdn not in groups['drbd']
          and ansible_hostname not in groups['drbd']
          and ansible_nodename not in groups['drbd'])
