- block:
  - name: Sends Custom OIDC CA to Greenlight
    synchronize:
      dest: /root/pki/oidc-ca.crt
      src: "{{ greenlight_oidc_ca_path }}"
  - include_role:
      name: pki
      tasks_from: install-ca.yaml
    vars:
      ca_path: /root/pki/oidc-ca.crt
      install_as: oidc
  when:
  - greenlight_oidc_ca_path | default(False)
  - greenlight_oidc_endpoint | default(False)
- block:
  - name: Sends Custom LDAP CA to Greenlight
    synchronize:
      dest: /root/pki/ldap-ca.crt
      src: "{{ greenlight_ldap_ca_path }}"
  - include_role:
      name: pki
      tasks_from: install-ca.yaml
    vars:
      ca_path: /root/pki/ldap-ca.crt
      install_as: ldap
  - include_role:
      name: commons
      tasks_from: ldap.yaml
    vars:
      ldap_endpoint: "{{ greenlight_ldap_endpoint }}"
  when:
  - greenlight_ldap_ca_path | default(False)
  - greenlight_ldap_endpoint | default(False)
