- name: "Reconfigures BigBlueButton Sending {{ greenlight_app_root }} to Geenlight"
  delegate_to: "{{ bbb }}"
  loop: "{{ groups['bbb'] }}"
  loop_control:
    loop_var: bbb
  register: conf_check
  template:
    dest: /etc/bigbluebutton/nginx/greenlight.nginx
    group: root
    mode: 0644
    owner: root
    src: "bbb-{{ 'proxy' if ((ansible_hostname in groups['bbb']
                              and ansible_hostname in groups['greenlight'])
                             or (ansible_fqdn in groups['bbb']
                                 and ansible_fqdn in groups['greenlight']))
                         else 'rewrite'
              }}.j2"
- name: Reloads Nginx on BigBlueButton Nodes
  delegate_to: "{{ bbb }}"
  loop: "{{ groups['bbb'] }}"
  loop_control:
    loop_var: bbb
  service:
    name: nginx
    state: restarted
  when:
  - conf_check is defined
  - conf_check is changed
