- name: Gather Facts from Postgres
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['postgres'] }}"
  loop_control:
    loop_var: srv
  setup:
- name: Gather Facts from BigBlueButton
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['bbb'] }}"
  loop_control:
    loop_var: srv
  setup:
  when:
  - groups['scalelite'] | length == 0
- name: Gather Facts from Scalelite
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['scalelite'] }}"
  loop_control:
    loop_var: srv
  setup:
  when:
  - groups['scalelite'] | length > 0
- name: Gather Facts from LBs
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['lb_front'] }}"
  loop_control:
    loop_var: srv
  setup:
  when:
  - groups['lb_front'] | length > 0
  - groups['scalelite'] | length > 1
