- name: Installs Greenlight Docker-Compose Directory
  file:
    dest: /etc/docker-compose/greenlight
    group: root
    mode: 0755
    owner: root
    state: directory
- include_role:
    name: docker
    tasks_from: check-pull.yaml
  vars:
    image_tag: "{{ greenlight_images_release }}"
    image_url: "{{ greenlight_images_repo }}"
