- name: Installs Greenlight Virtualhost
  notify: Reloads Nginx
  template:
    dest: /etc/nginx/sites-available/greenlight.conf
    group: root
    mode: 0644
    owner: root
    src: vhost.j2
- name: Enables Greenlight Virtualhost
  file:
    dest: /etc/nginx/sites-enabled/greenlight.conf
    src: /etc/nginx/sites-available/greenlight.conf
    state: link
  notify: Reloads Nginx
- include_role:
    name: nginx
    tasks_from: service.yaml
  vars:
    nginx_drbd_should_run: True
