- name: Fetches BigBlueButton API Secret
  args:
    executable: /bin/bash
  changed_when: False
  delegate_to: "{{ groups['bbb'][0] }}"
  register: bbb_secret
  run_once: yes
  shell: |
    set -o pipefail && \
    bbb-conf --secret | awk '/Secret:/{print $2}'
  when:
  - groups['scalelite'] | length == 0
- name: Installs BigBlueButton Conferences Streaming Platform Site Configuration
  notify: Reloads BBB CSP
  template:
    dest: /usr/src/bbb-csp/config.js
    group: "{{ bbbcsp_group }}"
    mode: 0640
    owner: root
    src: config.j2
- name: Installs BigBlueButton Conferences Streaming Platform API Configuration
  template:
    dest: /usr/src/bbb-csp/static/js/backend.js
    group: root
    mode: 0644
    owner: root
    src: backend.j2
- name: Installs BigBlueButton Conferences Streaming Platform Unit
  notify: Reloads BBB CSP
  register: bbbcsp_unit
  template:
    dest: /etc/systemd/system/bbbcsp.service
    group: root
    mode: 0644
    owner: root
    src: unit.j2
- name: Reloads Systemd Configuration
  systemd:
    daemon_reload: yes
  when:
  - bbbcsp_unit is defined
  - bbbcsp_unit is changed
- name: Ensures BigBlueButton Conferences Streaming Platform is Running & Starts on Boot
  service:
    enabled: yes
    name: bbbcsp
    state: started
