- name: Installs BigBlueButton Conferences Streaming Platform Site Configuration
  notify: Reloads BBB CSP
  template:
    dest: /usr/src/bbb-csp/config.js
    group: "{{ bbbcsp_group }}"
    mode: 0640
    owner: root
    src: config.j2
- name: Installs BigBlueButton Conferences Streaming Platform API Configuration
  template:
    dest: /usr/src/bbb-csp/static/js/backend.js
    group: root
    mode: 0644
    owner: root
    src: backend.j2
#- name: Installs BigBlueButton Conferences Streaming Platform PM2 Ecosystem
#  template:
#    dest: /usr/src/bbb-csp/ecosystem.config.js
#    group: root
#    mode: 0644
#    owner: root
#    src: ecosystem.j2
#- include_role:
#    name: nodejs
#    tasks_from: service.yaml
#  vars:
#    pm2_ecosystem_path: /usr/src/bbb-csp
#    pm2_runtime_homedir: /var/lib/pm2
#    pm2_runtime_user: "{{ bbbcsp_user }}"
- name: Installs BigBlueButton Conferences Streaming Platform Unit
  notify: Reloads BBB CSP
  register: bbbcsp_unit
  template:
    dest: /etc/systemd/system/bbbcsp.service
    group: root
    mode: 0644
    owner: root
    src: unit.j2
- name: Reloads Systemd Configuration
  shell: systemctl daemon-reload
  when:
  - bbbcsp_unit is defined
  - bbbcsp_unit is changed
- name: Ensures BigBlueButton Conferences Streaming Platform is Running & Starts on Boot
  service:
    enabled: yes
    name: bbbcsp
    state: started
