- name: Fails if BBB or PeerTube Missing
  fail:
    msg: |
      PeerTube and BigBlueButton - or Scalelite - required
  when:
  - >
      ((bigbluebutton_api_secret is not defined
        or greenlight_fqdn is not defined)
       and (groups['scalelite'] | length == 0
            and groups['bbb'] | length == 0))
      or (groups['peertube'] | length == 0
          and (peertube_rtmp_user is not defined
               or peertube_rtmp_password is not defined
               or peertube_fqdn is not defined))
- name: Gather Facts from PeerTube
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['peertube'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
- name: Gather Facts from BigBlueButton
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['bbb'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  vars:
    ansible_python_interpreter: /usr/bin/python
  when:
  - groups['scalelite'] | length == 0
  - groups['bbb'] | length > 0
- name: Gather Facts from Scalelite
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['scalelite'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['scalelite'] | length > 0
- name: Gather Facts from LBs
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['lb_front'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['lb_front'] | length > 0
  - groups['scalelite'] | length > 1
- name: Gather Facts from Reverse Proxies
  delegate_to: "{{ srv }}"
  delegate_facts: True
  loop: "{{ groups['reverse'] }}"
  loop_control:
    loop_var: srv
  run_once: yes
  setup:
  when:
  - groups['reverse'] | length > 0
  - groups['lb_front'] | length == 0
  - groups['scalelite'] | length > 1
