- name: Fetches Nginx Sources
  delay: 5
  get_url:
    dest: "/usr/src/{{ i.fl }}"
    group: root
    mode: 0644
    owner: root
    url: "{{ i.srcurl }}"
  loop:
  - srcurl: http://nginx.org/download/nginx-1.17.3.tar.gz
    fl: nginx.tar.gz
  - srcurl: https://github.com/arut/nginx-rtmp-module/archive/v1.2.1.zip
    fl: rtmp.zip
  - srcurl: http://www.zlib.net/zlib-1.2.11.tar.gz
    fl: zlib.tar.gz
  - srcurl: https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng/get/master.tar.gz
    fl: sticky.tar.gz
  loop_control:
    loop_var: i
  retries: 3
- name: Extracts Nginx Sources (tar)
  loop:
  - fl: nginx.tar.gz
    dr: nginx-1.17.3
  - fl: zlib.tar.gz
    dr: zlib-1.2.11
  - fl: sticky.tar.gz
    dr: nginx-goodies-nginx-sticky-module-ng-08a395c66e42
  loop_control:
    loop_var: i
  unarchive:
    creates: "/usr/src/{{ i.dr }}"
    dest: /usr/src
    remote_src: yes
    src: "/usr/src/{{ i.fl }}"
- name: Extracts Nginx Sources (zip)
  unarchive:
    creates: /usr/src/nginx-rtmp-module-1.2.1
    dest: /usr/src
    remote_src: yes
    src: /usr/src/rtmp.zip
- name: Prepares to Build Nginx
  args:
    chdir: /usr/src/nginx-1.17.3
    creates: /usr/src/nginx-1.17.3/configure.log
  environment:
    PATH: /usr/src/nginx-1.17.3:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  shell: |
    configure --with-http_ssl_module --with-http_v2_module --with-http_auth_request_module --add-module=../nginx-rtmp-module-1.2.1 \
      --add-module=../nginx-goodies-nginx-sticky-module-ng-08a395c66e42 --with-zlib=../zlib-1.2.11 --with-cc-opt="-Wimplicit-fallthrough=0" \
      >configure.log 2>&1
- name: Builds and Installs Nginx
  args:
    chdir: /usr/src/nginx-1.17.3
    creates: /usr/src/nginx-1.17.3/install.log
  shell: make install >install.log 2>&1
- name: Installs Nginx Systemd Unit
  copy:
    dest: /etc/systemd/system/nginx-osp.service
    group: root
    mode: 0644
    owner: root
    remote_src: yes
    src: /usr/src/openstreamingplatform/setup/nginx/nginx-osp.service
  register: nginx_unit
- name: Reloads Systemd Configuration
  systemd:
    daemon_reload: yes
  when:
  - nginx_unit is defined
  - nginx_unit is changed
