---
dependencies:
- role: docker
- role: nginx
  vars:
    nginx_drbd_should_run: True
  when:
  - >
     not (ansible_fqdn in groups['bbb']
          and ansible_fqdn in groups['greenlight'])
  - >
     not (ansible_hostname in groups['bbb']
          and ansible_hostname in groups['greenlight'])
  - >
     not (ansible_nodename in groups['bbb']
          and ansible_nodename in groups['greenlight'])
