- name: "Installs Postgres Exporter Unit (db={{ postgres_exporter_db }})"
  register: exporter_unit
  template:
    dest: "/etc/systemd/system/postgres-exporter-{{ postgres_exporter_db }}.service"
    group: root
    mode: 0644
    owner: root
    src: exporter.j2
- name: "Installs Postgres Exporter Configuration (db={{ postgres_exporter_db }})"
  register: exporter_config
  template:
    dest: "/etc/default/postgres-exporter-{{ postgres_exporter_db }}"
    group: postgresexporter
    mode: 0640
    owner: root
    src: xp-defaults.j2
- name: "Reloads Systemd Configuration (db={{ postgres_exporter_db }})"
  systemd:
    daemon_reload: yes
  register: reconfigured
  when:
  - >
      (exporter_unit is defined
      and exporter_unit is changed)
      or (exporter_config is defined
      and exporter_config is changed)
- block:
  - name: "Ensures Postgres Exporter is Running & Starts on Boot (db={{ postgres_exporter_db }})"
    register: restarted
    service:
      enabled: yes
      name: "postgres-exporter-{{ postgres_exporter_db }}"
      state: started
  - name: "Restarts Postgres Exporter (db={{ postgres_exporter_db }})"
    register: restarted
    service:
      name: "postgres-exporter-{{ postgres_exporter_db }}"
      state: restarted
    when:
    - reconfigured is defined
    - reconfigured is changed
    - restarted is defined
    - not (restarted is changed)
  when:
  - ansible_fqdn not in groups['drbd']
  - ansible_nodename not in groups['drbd']
  - ansible_hostname not in groups['drbd']
- block:
  - name: Ensures Postgres Exporter is Disabled on DRBD Members
    service:
      enabled: no
      name: "postgres-exporter-{{ postgres_exporter_db }}"
  - name: Ensures Postgres Exporter is Stopped on DRBD Backup Members
    service:
      name: "postgres-exporter-{{ postgres_exporter_db }}"
      state: stopped
    when:
    - not (drbd_is_primary | default(False))
  - include_role:
      name: pacemaker
      tasks_from: add-service.yaml
    loop: "{{ postgres_drbd_groups }}"
    loop_control:
      loop_var: apply_to
    vars:
      service_id: Postgresqlxp-rsc
      service_name: "postgres-exporter-{{ postgres_exporter_db }}"
      service_type: systemd
    when:
    - groups[apply_to] | length > 0
    - >
        ansible_nodename in groups[apply_to]
        or ansible_hostname in groups[apply_to]
        or ansible_fqdn in groups[apply_to]
  - include_role:
      name: pacemaker
      tasks_from: finish-setup.yaml
    loop: "{{ postgres_drbd_groups }}"
    loop_control:
      loop_var: apply_to
    vars:
      drbd_facts_reset: False
    when:
    - groups[apply_to] | length > 0
    - >
        ansible_nodename in groups[apply_to]
        or ansible_hostname in groups[apply_to]
        or ansible_fqdn in groups[apply_to]
  when:
  - >
      ansible_fqdn in groups['drbd']
      or ansible_hostname in groups['drbd']
      or ansible_nodename in groups['drbd']
  - corosync_hostgroup | default(False)
