firehol_app_filtered_ports:
- name: postgres
  value: tcp/5432
firehol_app_opened_ports:
- name: ssh
  value: tcp/22
- name: nodexp
  value: tcp/9142
- name: postgresxp
  value: tcp/9144
- name: systemdxp
  value: tcp/9147
