firehol_app_filtered_ports:
- name: ssh
  value: tcp/22
- name: nodexp
  value: tcp/9142
- name: nginxxp
  value: tcp/9143
- name: nginxluaxp
  value: tcp/9145
- name: systemdxp
  value: tcp/9147
firehol_app_opened_ports:
- name: http
  value: tcp/80
- name: https
  value: tcp/443
firehol_opened_ports: []
