- name: Removes Coturn Log File
  file:
    dest: "{{ item }}"
    state: absent
  loop:
  - /var/log/coturn.log
  - /etc/logrotate.d/coturn.conf
- name: Disables IPv6
  copy:
    dest: /etc/sysctl.d/99-nov6.conf
    group: root
    mode: 0644
    owner: root
    src: nov6.conf
  register: sysconf
- name: Ensures /etc/hosts would not mention IPv6 Addresses
  lineinfile:
    dest: /etc/hosts
    regex: "^{{ item }}"
    state: absent
  loop:
  - "::1"
  - ff0
- name: Reloads Sysctl Configuration
  args:
    chdir: /etc/sysctl.d
  shell: |
    while read config; do sysctl -w $config; done <99-nov6.conf
  when:
  - sysconf is defined
  - sysconf is changed
- name: Installs Coturn Configuration
  register: config_changed
  template:
    dest: /etc/turnserver.conf
    group: root
    mode: 0640
    owner: root
    src: coturn.j2
- name: Enables Coturn Service
  register: should_reload
  lineinfile:
    dest: /etc/default/coturn
    line: "TURNSERVER_ENABLED=1"
    regexp: ^TURNSERVER_ENABLED=
- name: Ensures Coturn is Running & Starts on Boot
  register: did_start
  service:
    enabled: yes
    name: coturn
    state: started
- name: Restarts Coturn
  service:
    name: coturn
    state: restarted
  when:
  - did_start is defined
  - not (did_start is changed)
  - >
      (should_reload is defined
       and should_reload is changed)
      or (config_changed is defined
       and config_changed is changed)
      or (unit_configured is defined
       and unit_configured is changed)
