- include_tasks: install.yaml
- block:
  - include_tasks: facts.yaml
  - include_tasks: dbinit.yaml
  when:
  - groups['postgres_coturn'] | length > 0
- include_tasks: ssl.yaml
- include_tasks: configure.yaml
- include_tasks: utils.yaml
